/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: DisplayServer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "DisplayServer.pb-c.h"
void   manager_test__init
                     (ManagerTest         *message)
{
  static ManagerTest init_value = MANAGER_TEST__INIT;
  *message = init_value;
}
size_t manager_test__get_packed_size
                     (const ManagerTest *message)
{
  assert(message->base.descriptor == &manager_test__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t manager_test__pack
                     (const ManagerTest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &manager_test__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t manager_test__pack_to_buffer
                     (const ManagerTest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &manager_test__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ManagerTest *
       manager_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ManagerTest *)
     protobuf_c_message_unpack (&manager_test__descriptor,
                                allocator, len, data);
}
void   manager_test__free_unpacked
                     (ManagerTest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &manager_test__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor manager_test__field_descriptors[1] =
{
  {
    "dialogue",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ManagerTest, dialogue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned manager_test__field_indices_by_name[] = {
  0,   /* field[0] = dialogue */
};
static const ProtobufCIntRange manager_test__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor manager_test__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ManagerTest",
  "ManagerTest",
  "ManagerTest",
  "",
  sizeof(ManagerTest),
  1,
  manager_test__field_descriptors,
  manager_test__field_indices_by_name,
  1,  manager_test__number_ranges,
  (ProtobufCMessageInit) manager_test__init,
  NULL,NULL,NULL    /* reserved[123] */
};
