/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: MasterServer.proto */

#ifndef PROTOBUF_C_MasterServer_2eproto__INCLUDED
#define PROTOBUF_C_MasterServer_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ManagerTest ManagerTest;
typedef struct _GcodeCmd GcodeCmd;
typedef struct _GcodeCmdRes GcodeCmdRes;
typedef struct _AxisPara AxisPara;
typedef struct _AudioNum AudioNum;
typedef struct _ControlRange ControlRange;
typedef struct _GcodePhotoInfoRes GcodePhotoInfoRes;
typedef struct _CurMcuVersion CurMcuVersion;
typedef struct _CurMcuVersionList CurMcuVersionList;


/* --- enums --- */


/* --- messages --- */

struct  _ManagerTest
{
  ProtobufCMessage base;
  char *dialogue;
};
#define MANAGER_TEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&manager_test__descriptor) \
    , NULL }


/*
 * gcode命令
 */
struct  _GcodeCmd
{
  ProtobufCMessage base;
  /*
   * 打印指令
   */
  protobuf_c_boolean has_cmdstr;
  ProtobufCBinaryData cmdstr;
};
#define GCODE_CMD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gcode_cmd__descriptor) \
    , 0,{0,NULL} }


/*
 * gcode命令应答
 */
struct  _GcodeCmdRes
{
  ProtobufCMessage base;
  /*
   * 响应结果
   */
  uint32_t result;
  /*
   * 结果内容
   */
  protobuf_c_boolean has_resstr;
  ProtobufCBinaryData resstr;
};
#define GCODE_CMD_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gcode_cmd_res__descriptor) \
    , 0, 0,{0,NULL} }


/*
 * 坐标参数
 */
struct  _AxisPara
{
  ProtobufCMessage base;
  protobuf_c_boolean has_x;
  int32_t x;
  protobuf_c_boolean has_y;
  int32_t y;
  protobuf_c_boolean has_z;
  int32_t z;
  protobuf_c_boolean has_e;
  int32_t e;
};
#define AXIS_PARA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&axis_para__descriptor) \
    , 0,0, 0,0, 0,0, 0,0 }


/*
 * 音频播报
 */
struct  _AudioNum
{
  ProtobufCMessage base;
  uint32_t data;
};
#define AUDIO_NUM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio_num__descriptor) \
    , 0 }


/*
 * 设置获取SD文件范围
 */
struct  _ControlRange
{
  ProtobufCMessage base;
  /*
   * 结果
   */
  protobuf_c_boolean has_result;
  uint32_t result;
  /*
   * 开始
   */
  protobuf_c_boolean has_start;
  uint32_t start;
  /*
   * 停止
   */
  protobuf_c_boolean has_end;
  uint32_t end;
};
#define CONTROL_RANGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_range__descriptor) \
    , 0,0, 0,0, 0,0 }


/*
 * 从SD的gcode文件获取注水图
 */
struct  _GcodePhotoInfoRes
{
  ProtobufCMessage base;
  /*
   * 响应结果
   */
  uint32_t result;
  /*
   * 起始像素点
   */
  uint32_t start_pixel;
  /*
   * 结束像素点
   */
  uint32_t end_pixel;
  /*
   * 模型高度
   */
  uint32_t model_height;
  /*
   * 模型层高
   */
  uint32_t layer_height;
  /*
   * 预览图路径
   */
  ProtobufCBinaryData path;
};
#define GCODE_PHOTO_INFO_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gcode_photo_info_res__descriptor) \
    , 0, 0, 0, 0, 0, {0,NULL} }


/*
 * 下位机软硬件信息
 */
struct  _CurMcuVersion
{
  ProtobufCMessage base;
  /*
   * 软件版本
   */
  protobuf_c_boolean has_software;
  ProtobufCBinaryData software;
  /*
   * 硬件版本
   */
  protobuf_c_boolean has_hardware;
  ProtobufCBinaryData hardware;
};
#define CUR_MCU_VERSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cur_mcu_version__descriptor) \
    , 0,{0,NULL}, 0,{0,NULL} }


/*
 * 下位机软硬件信息列表
 */
struct  _CurMcuVersionList
{
  ProtobufCMessage base;
  /*
   * 运动下位机
   */
  CurMcuVersion *hostmcu;
  /*
   * 喷嘴下位机
   */
  CurMcuVersion *nozzlemcu;
  /*
   * 热床下位机
   */
  CurMcuVersion *bedmcu;
};
#define CUR_MCU_VERSION_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cur_mcu_version_list__descriptor) \
    , NULL, NULL, NULL }


/* ManagerTest methods */
void   manager_test__init
                     (ManagerTest         *message);
size_t manager_test__get_packed_size
                     (const ManagerTest   *message);
size_t manager_test__pack
                     (const ManagerTest   *message,
                      uint8_t             *out);
size_t manager_test__pack_to_buffer
                     (const ManagerTest   *message,
                      ProtobufCBuffer     *buffer);
ManagerTest *
       manager_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   manager_test__free_unpacked
                     (ManagerTest *message,
                      ProtobufCAllocator *allocator);
/* GcodeCmd methods */
void   gcode_cmd__init
                     (GcodeCmd         *message);
size_t gcode_cmd__get_packed_size
                     (const GcodeCmd   *message);
size_t gcode_cmd__pack
                     (const GcodeCmd   *message,
                      uint8_t             *out);
size_t gcode_cmd__pack_to_buffer
                     (const GcodeCmd   *message,
                      ProtobufCBuffer     *buffer);
GcodeCmd *
       gcode_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gcode_cmd__free_unpacked
                     (GcodeCmd *message,
                      ProtobufCAllocator *allocator);
/* GcodeCmdRes methods */
void   gcode_cmd_res__init
                     (GcodeCmdRes         *message);
size_t gcode_cmd_res__get_packed_size
                     (const GcodeCmdRes   *message);
size_t gcode_cmd_res__pack
                     (const GcodeCmdRes   *message,
                      uint8_t             *out);
size_t gcode_cmd_res__pack_to_buffer
                     (const GcodeCmdRes   *message,
                      ProtobufCBuffer     *buffer);
GcodeCmdRes *
       gcode_cmd_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gcode_cmd_res__free_unpacked
                     (GcodeCmdRes *message,
                      ProtobufCAllocator *allocator);
/* AxisPara methods */
void   axis_para__init
                     (AxisPara         *message);
size_t axis_para__get_packed_size
                     (const AxisPara   *message);
size_t axis_para__pack
                     (const AxisPara   *message,
                      uint8_t             *out);
size_t axis_para__pack_to_buffer
                     (const AxisPara   *message,
                      ProtobufCBuffer     *buffer);
AxisPara *
       axis_para__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   axis_para__free_unpacked
                     (AxisPara *message,
                      ProtobufCAllocator *allocator);
/* AudioNum methods */
void   audio_num__init
                     (AudioNum         *message);
size_t audio_num__get_packed_size
                     (const AudioNum   *message);
size_t audio_num__pack
                     (const AudioNum   *message,
                      uint8_t             *out);
size_t audio_num__pack_to_buffer
                     (const AudioNum   *message,
                      ProtobufCBuffer     *buffer);
AudioNum *
       audio_num__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio_num__free_unpacked
                     (AudioNum *message,
                      ProtobufCAllocator *allocator);
/* ControlRange methods */
void   control_range__init
                     (ControlRange         *message);
size_t control_range__get_packed_size
                     (const ControlRange   *message);
size_t control_range__pack
                     (const ControlRange   *message,
                      uint8_t             *out);
size_t control_range__pack_to_buffer
                     (const ControlRange   *message,
                      ProtobufCBuffer     *buffer);
ControlRange *
       control_range__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_range__free_unpacked
                     (ControlRange *message,
                      ProtobufCAllocator *allocator);
/* GcodePhotoInfoRes methods */
void   gcode_photo_info_res__init
                     (GcodePhotoInfoRes         *message);
size_t gcode_photo_info_res__get_packed_size
                     (const GcodePhotoInfoRes   *message);
size_t gcode_photo_info_res__pack
                     (const GcodePhotoInfoRes   *message,
                      uint8_t             *out);
size_t gcode_photo_info_res__pack_to_buffer
                     (const GcodePhotoInfoRes   *message,
                      ProtobufCBuffer     *buffer);
GcodePhotoInfoRes *
       gcode_photo_info_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gcode_photo_info_res__free_unpacked
                     (GcodePhotoInfoRes *message,
                      ProtobufCAllocator *allocator);
/* CurMcuVersion methods */
void   cur_mcu_version__init
                     (CurMcuVersion         *message);
size_t cur_mcu_version__get_packed_size
                     (const CurMcuVersion   *message);
size_t cur_mcu_version__pack
                     (const CurMcuVersion   *message,
                      uint8_t             *out);
size_t cur_mcu_version__pack_to_buffer
                     (const CurMcuVersion   *message,
                      ProtobufCBuffer     *buffer);
CurMcuVersion *
       cur_mcu_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cur_mcu_version__free_unpacked
                     (CurMcuVersion *message,
                      ProtobufCAllocator *allocator);
/* CurMcuVersionList methods */
void   cur_mcu_version_list__init
                     (CurMcuVersionList         *message);
size_t cur_mcu_version_list__get_packed_size
                     (const CurMcuVersionList   *message);
size_t cur_mcu_version_list__pack
                     (const CurMcuVersionList   *message,
                      uint8_t             *out);
size_t cur_mcu_version_list__pack_to_buffer
                     (const CurMcuVersionList   *message,
                      ProtobufCBuffer     *buffer);
CurMcuVersionList *
       cur_mcu_version_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cur_mcu_version_list__free_unpacked
                     (CurMcuVersionList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ManagerTest_Closure)
                 (const ManagerTest *message,
                  void *closure_data);
typedef void (*GcodeCmd_Closure)
                 (const GcodeCmd *message,
                  void *closure_data);
typedef void (*GcodeCmdRes_Closure)
                 (const GcodeCmdRes *message,
                  void *closure_data);
typedef void (*AxisPara_Closure)
                 (const AxisPara *message,
                  void *closure_data);
typedef void (*AudioNum_Closure)
                 (const AudioNum *message,
                  void *closure_data);
typedef void (*ControlRange_Closure)
                 (const ControlRange *message,
                  void *closure_data);
typedef void (*GcodePhotoInfoRes_Closure)
                 (const GcodePhotoInfoRes *message,
                  void *closure_data);
typedef void (*CurMcuVersion_Closure)
                 (const CurMcuVersion *message,
                  void *closure_data);
typedef void (*CurMcuVersionList_Closure)
                 (const CurMcuVersionList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor manager_test__descriptor;
extern const ProtobufCMessageDescriptor gcode_cmd__descriptor;
extern const ProtobufCMessageDescriptor gcode_cmd_res__descriptor;
extern const ProtobufCMessageDescriptor axis_para__descriptor;
extern const ProtobufCMessageDescriptor audio_num__descriptor;
extern const ProtobufCMessageDescriptor control_range__descriptor;
extern const ProtobufCMessageDescriptor gcode_photo_info_res__descriptor;
extern const ProtobufCMessageDescriptor cur_mcu_version__descriptor;
extern const ProtobufCMessageDescriptor cur_mcu_version_list__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_MasterServer_2eproto__INCLUDED */
