/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: MasterServer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "MasterServer.pb-c.h"
void   manager_test__init
                     (ManagerTest         *message)
{
  static ManagerTest init_value = MANAGER_TEST__INIT;
  *message = init_value;
}
size_t manager_test__get_packed_size
                     (const ManagerTest *message)
{
  assert(message->base.descriptor == &manager_test__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t manager_test__pack
                     (const ManagerTest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &manager_test__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t manager_test__pack_to_buffer
                     (const ManagerTest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &manager_test__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ManagerTest *
       manager_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ManagerTest *)
     protobuf_c_message_unpack (&manager_test__descriptor,
                                allocator, len, data);
}
void   manager_test__free_unpacked
                     (ManagerTest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &manager_test__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gcode_cmd__init
                     (GcodeCmd         *message)
{
  static GcodeCmd init_value = GCODE_CMD__INIT;
  *message = init_value;
}
size_t gcode_cmd__get_packed_size
                     (const GcodeCmd *message)
{
  assert(message->base.descriptor == &gcode_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gcode_cmd__pack
                     (const GcodeCmd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gcode_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gcode_cmd__pack_to_buffer
                     (const GcodeCmd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gcode_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GcodeCmd *
       gcode_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GcodeCmd *)
     protobuf_c_message_unpack (&gcode_cmd__descriptor,
                                allocator, len, data);
}
void   gcode_cmd__free_unpacked
                     (GcodeCmd *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &gcode_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gcode_cmd_res__init
                     (GcodeCmdRes         *message)
{
  static GcodeCmdRes init_value = GCODE_CMD_RES__INIT;
  *message = init_value;
}
size_t gcode_cmd_res__get_packed_size
                     (const GcodeCmdRes *message)
{
  assert(message->base.descriptor == &gcode_cmd_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gcode_cmd_res__pack
                     (const GcodeCmdRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gcode_cmd_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gcode_cmd_res__pack_to_buffer
                     (const GcodeCmdRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gcode_cmd_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GcodeCmdRes *
       gcode_cmd_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GcodeCmdRes *)
     protobuf_c_message_unpack (&gcode_cmd_res__descriptor,
                                allocator, len, data);
}
void   gcode_cmd_res__free_unpacked
                     (GcodeCmdRes *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &gcode_cmd_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axis_para__init
                     (AxisPara         *message)
{
  static AxisPara init_value = AXIS_PARA__INIT;
  *message = init_value;
}
size_t axis_para__get_packed_size
                     (const AxisPara *message)
{
  assert(message->base.descriptor == &axis_para__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axis_para__pack
                     (const AxisPara *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axis_para__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axis_para__pack_to_buffer
                     (const AxisPara *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axis_para__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AxisPara *
       axis_para__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AxisPara *)
     protobuf_c_message_unpack (&axis_para__descriptor,
                                allocator, len, data);
}
void   axis_para__free_unpacked
                     (AxisPara *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &axis_para__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   audio_num__init
                     (AudioNum         *message)
{
  static AudioNum init_value = AUDIO_NUM__INIT;
  *message = init_value;
}
size_t audio_num__get_packed_size
                     (const AudioNum *message)
{
  assert(message->base.descriptor == &audio_num__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t audio_num__pack
                     (const AudioNum *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &audio_num__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t audio_num__pack_to_buffer
                     (const AudioNum *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &audio_num__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AudioNum *
       audio_num__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AudioNum *)
     protobuf_c_message_unpack (&audio_num__descriptor,
                                allocator, len, data);
}
void   audio_num__free_unpacked
                     (AudioNum *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &audio_num__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   control_range__init
                     (ControlRange         *message)
{
  static ControlRange init_value = CONTROL_RANGE__INIT;
  *message = init_value;
}
size_t control_range__get_packed_size
                     (const ControlRange *message)
{
  assert(message->base.descriptor == &control_range__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t control_range__pack
                     (const ControlRange *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &control_range__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t control_range__pack_to_buffer
                     (const ControlRange *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &control_range__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ControlRange *
       control_range__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ControlRange *)
     protobuf_c_message_unpack (&control_range__descriptor,
                                allocator, len, data);
}
void   control_range__free_unpacked
                     (ControlRange *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &control_range__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gcode_photo_info_res__init
                     (GcodePhotoInfoRes         *message)
{
  static GcodePhotoInfoRes init_value = GCODE_PHOTO_INFO_RES__INIT;
  *message = init_value;
}
size_t gcode_photo_info_res__get_packed_size
                     (const GcodePhotoInfoRes *message)
{
  assert(message->base.descriptor == &gcode_photo_info_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gcode_photo_info_res__pack
                     (const GcodePhotoInfoRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gcode_photo_info_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gcode_photo_info_res__pack_to_buffer
                     (const GcodePhotoInfoRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gcode_photo_info_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GcodePhotoInfoRes *
       gcode_photo_info_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GcodePhotoInfoRes *)
     protobuf_c_message_unpack (&gcode_photo_info_res__descriptor,
                                allocator, len, data);
}
void   gcode_photo_info_res__free_unpacked
                     (GcodePhotoInfoRes *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &gcode_photo_info_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cur_mcu_version__init
                     (CurMcuVersion         *message)
{
  static CurMcuVersion init_value = CUR_MCU_VERSION__INIT;
  *message = init_value;
}
size_t cur_mcu_version__get_packed_size
                     (const CurMcuVersion *message)
{
  assert(message->base.descriptor == &cur_mcu_version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cur_mcu_version__pack
                     (const CurMcuVersion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cur_mcu_version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cur_mcu_version__pack_to_buffer
                     (const CurMcuVersion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cur_mcu_version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CurMcuVersion *
       cur_mcu_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CurMcuVersion *)
     protobuf_c_message_unpack (&cur_mcu_version__descriptor,
                                allocator, len, data);
}
void   cur_mcu_version__free_unpacked
                     (CurMcuVersion *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cur_mcu_version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cur_mcu_version_list__init
                     (CurMcuVersionList         *message)
{
  static CurMcuVersionList init_value = CUR_MCU_VERSION_LIST__INIT;
  *message = init_value;
}
size_t cur_mcu_version_list__get_packed_size
                     (const CurMcuVersionList *message)
{
  assert(message->base.descriptor == &cur_mcu_version_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cur_mcu_version_list__pack
                     (const CurMcuVersionList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cur_mcu_version_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cur_mcu_version_list__pack_to_buffer
                     (const CurMcuVersionList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cur_mcu_version_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CurMcuVersionList *
       cur_mcu_version_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CurMcuVersionList *)
     protobuf_c_message_unpack (&cur_mcu_version_list__descriptor,
                                allocator, len, data);
}
void   cur_mcu_version_list__free_unpacked
                     (CurMcuVersionList *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cur_mcu_version_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor manager_test__field_descriptors[1] =
{
  {
    "dialogue",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ManagerTest, dialogue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned manager_test__field_indices_by_name[] = {
  0,   /* field[0] = dialogue */
};
static const ProtobufCIntRange manager_test__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor manager_test__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ManagerTest",
  "ManagerTest",
  "ManagerTest",
  "",
  sizeof(ManagerTest),
  1,
  manager_test__field_descriptors,
  manager_test__field_indices_by_name,
  1,  manager_test__number_ranges,
  (ProtobufCMessageInit) manager_test__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gcode_cmd__field_descriptors[1] =
{
  {
    "cmdStr",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(GcodeCmd, has_cmdstr),
    offsetof(GcodeCmd, cmdstr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gcode_cmd__field_indices_by_name[] = {
  0,   /* field[0] = cmdStr */
};
static const ProtobufCIntRange gcode_cmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gcode_cmd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GcodeCmd",
  "GcodeCmd",
  "GcodeCmd",
  "",
  sizeof(GcodeCmd),
  1,
  gcode_cmd__field_descriptors,
  gcode_cmd__field_indices_by_name,
  1,  gcode_cmd__number_ranges,
  (ProtobufCMessageInit) gcode_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gcode_cmd_res__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GcodeCmdRes, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resStr",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(GcodeCmdRes, has_resstr),
    offsetof(GcodeCmdRes, resstr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gcode_cmd_res__field_indices_by_name[] = {
  1,   /* field[1] = resStr */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange gcode_cmd_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gcode_cmd_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GcodeCmdRes",
  "GcodeCmdRes",
  "GcodeCmdRes",
  "",
  sizeof(GcodeCmdRes),
  2,
  gcode_cmd_res__field_descriptors,
  gcode_cmd_res__field_indices_by_name,
  1,  gcode_cmd_res__number_ranges,
  (ProtobufCMessageInit) gcode_cmd_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axis_para__field_descriptors[4] =
{
  {
    "X",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(AxisPara, has_x),
    offsetof(AxisPara, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Y",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(AxisPara, has_y),
    offsetof(AxisPara, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Z",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(AxisPara, has_z),
    offsetof(AxisPara, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "E",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(AxisPara, has_e),
    offsetof(AxisPara, e),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axis_para__field_indices_by_name[] = {
  3,   /* field[3] = E */
  0,   /* field[0] = X */
  1,   /* field[1] = Y */
  2,   /* field[2] = Z */
};
static const ProtobufCIntRange axis_para__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axis_para__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AxisPara",
  "AxisPara",
  "AxisPara",
  "",
  sizeof(AxisPara),
  4,
  axis_para__field_descriptors,
  axis_para__field_indices_by_name,
  1,  axis_para__number_ranges,
  (ProtobufCMessageInit) axis_para__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor audio_num__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AudioNum, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned audio_num__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange audio_num__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor audio_num__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AudioNum",
  "AudioNum",
  "AudioNum",
  "",
  sizeof(AudioNum),
  1,
  audio_num__field_descriptors,
  audio_num__field_indices_by_name,
  1,  audio_num__number_ranges,
  (ProtobufCMessageInit) audio_num__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor control_range__field_descriptors[3] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ControlRange, has_result),
    offsetof(ControlRange, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ControlRange, has_start),
    offsetof(ControlRange, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ControlRange, has_end),
    offsetof(ControlRange, end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned control_range__field_indices_by_name[] = {
  2,   /* field[2] = end */
  0,   /* field[0] = result */
  1,   /* field[1] = start */
};
static const ProtobufCIntRange control_range__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor control_range__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ControlRange",
  "ControlRange",
  "ControlRange",
  "",
  sizeof(ControlRange),
  3,
  control_range__field_descriptors,
  control_range__field_indices_by_name,
  1,  control_range__number_ranges,
  (ProtobufCMessageInit) control_range__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gcode_photo_info_res__field_descriptors[6] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GcodePhotoInfoRes, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_pixel",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GcodePhotoInfoRes, start_pixel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_pixel",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GcodePhotoInfoRes, end_pixel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model_height",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GcodePhotoInfoRes, model_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "layer_height",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GcodePhotoInfoRes, layer_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GcodePhotoInfoRes, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gcode_photo_info_res__field_indices_by_name[] = {
  2,   /* field[2] = end_pixel */
  4,   /* field[4] = layer_height */
  3,   /* field[3] = model_height */
  5,   /* field[5] = path */
  0,   /* field[0] = result */
  1,   /* field[1] = start_pixel */
};
static const ProtobufCIntRange gcode_photo_info_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor gcode_photo_info_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GcodePhotoInfoRes",
  "GcodePhotoInfoRes",
  "GcodePhotoInfoRes",
  "",
  sizeof(GcodePhotoInfoRes),
  6,
  gcode_photo_info_res__field_descriptors,
  gcode_photo_info_res__field_indices_by_name,
  1,  gcode_photo_info_res__number_ranges,
  (ProtobufCMessageInit) gcode_photo_info_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cur_mcu_version__field_descriptors[2] =
{
  {
    "software",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CurMcuVersion, has_software),
    offsetof(CurMcuVersion, software),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hardware",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CurMcuVersion, has_hardware),
    offsetof(CurMcuVersion, hardware),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cur_mcu_version__field_indices_by_name[] = {
  1,   /* field[1] = hardware */
  0,   /* field[0] = software */
};
static const ProtobufCIntRange cur_mcu_version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cur_mcu_version__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CurMcuVersion",
  "CurMcuVersion",
  "CurMcuVersion",
  "",
  sizeof(CurMcuVersion),
  2,
  cur_mcu_version__field_descriptors,
  cur_mcu_version__field_indices_by_name,
  1,  cur_mcu_version__number_ranges,
  (ProtobufCMessageInit) cur_mcu_version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cur_mcu_version_list__field_descriptors[3] =
{
  {
    "hostMcu",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CurMcuVersionList, hostmcu),
    &cur_mcu_version__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nozzleMcu",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CurMcuVersionList, nozzlemcu),
    &cur_mcu_version__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bedMcu",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CurMcuVersionList, bedmcu),
    &cur_mcu_version__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cur_mcu_version_list__field_indices_by_name[] = {
  2,   /* field[2] = bedMcu */
  0,   /* field[0] = hostMcu */
  1,   /* field[1] = nozzleMcu */
};
static const ProtobufCIntRange cur_mcu_version_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cur_mcu_version_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CurMcuVersionList",
  "CurMcuVersionList",
  "CurMcuVersionList",
  "",
  sizeof(CurMcuVersionList),
  3,
  cur_mcu_version_list__field_descriptors,
  cur_mcu_version_list__field_indices_by_name,
  1,  cur_mcu_version_list__number_ranges,
  (ProtobufCMessageInit) cur_mcu_version_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
