/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: AudioServer.proto */

#ifndef PROTOBUF_C_AudioServer_2eproto__INCLUDED
#define PROTOBUF_C_AudioServer_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ManagerTest ManagerTest;


/* --- enums --- */


/* --- messages --- */

struct  _ManagerTest
{
  ProtobufCMessage base;
  char *dialogue;
};
#define MANAGER_TEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&manager_test__descriptor) \
    , NULL }


/* ManagerTest methods */
void   manager_test__init
                     (ManagerTest         *message);
size_t manager_test__get_packed_size
                     (const ManagerTest   *message);
size_t manager_test__pack
                     (const ManagerTest   *message,
                      uint8_t             *out);
size_t manager_test__pack_to_buffer
                     (const ManagerTest   *message,
                      ProtobufCBuffer     *buffer);
ManagerTest *
       manager_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   manager_test__free_unpacked
                     (ManagerTest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ManagerTest_Closure)
                 (const ManagerTest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor manager_test__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_AudioServer_2eproto__INCLUDED */
