/*
 * @Description : 
 * @Author      : Yufeng Zhang
 * @Date: 2021-12-06 20:56:59
 * @LastEditTime: 2023-10-30 11:07:39
 */

#ifndef __MSG_BASE_H__
#define __MSG_BASE_H__

#include <stdint.h>
#include <pthread.h>
#include <regex.h>

#include "global/Global.h"
#include "Base/Proto/MasterServer.pb-c.h"
#include "Base/ShareState/ShareState.h"
#include "Base/SaveFile/SaveFile.h"
#include "Base/RingBuff/RingBuff.h"
#include "Base/KlipperConfig/ConfigAnl.h"
#include "Base/PluginGcode/gcode_point.h"

#ifdef  __cplusplus  
extern "C" {  
#endif

/**
 * @description: 实时线程优先级
 * @param  {*}
 * @return {*}
 */
typedef enum {
    SERIAL_PORT_RECV_THREAD_PRIORITY = 30,
    GET_GCODE_CMD_THREAD_PRIORITY = 40,
    SERIAL_PORT_SEND_THREAD_PRIORITY = 50,
}ThreadPriority_t;

/**
 * @description: 变量定义
 * @param  {*}
 * @return {*}
 */
typedef struct{
    pthread_t handle;
    int (*sendMsgBuff)(MsgHeadBuf_t *data, size_t len);
}MsgHandle_t;

/**
 * @description: 全局变量声明
 * @return {*}
 */
extern MsgHandle_t *wifiManager;
extern MsgHandle_t *displayManager;
extern MsgHandle_t *audioManager;
extern MsgHandle_t *appManager;
extern MsgHandle_t *webManager;
extern MsgHandle_t *upgradeManager;
extern MsgHandle_t *burnManager;
extern MsgHandle_t *controller;
extern MsgHandle_t *appointment;
extern MsgHandle_t *sysTransfer;

#define MANAGER_MSG_SEND(a, b, c)                                                                                   \
    switch (a) {                                                                                                    \
        case MSG_ORIGIN_WIFI_MANAGER:   { if(wifiManager)       wifiManager->sendMsgBuff(b, c); }       break;      \
        case MSG_ORIGIN_DISPLAY_MANAGER:{ if(displayManager)    displayManager->sendMsgBuff(b, c); }    break;      \
        case MSG_ORIGIN_AUDIO_MANAGER:  { if(audioManager)      audioManager->sendMsgBuff(b, c); }      break;      \
        case MSG_ORIGIN_APP_MANAGER:    { if(appManager)        appManager->sendMsgBuff(b, c); }        break;      \
        case MSG_ORIGIN_WEB_MANAGER:    { if(webManager)        webManager->sendMsgBuff(b, c); }        break;      \
        case MSG_ORIGIN_UPGRADE_MANAGER:{ if(upgradeManager)    upgradeManager->sendMsgBuff(b, c); }    break;      \
        case MSG_ORIGIN_BURN_MANAGER:   { if(burnManager)       burnManager->sendMsgBuff(b, c); }       break;      \
        case MSG_ORIGIN_CONTROLLER:     { if(controller)        controller->sendMsgBuff(b, c); }        break;      \
        case MSG_ORIGIN_APPOINTMENT:    { if(appointment)       appointment->sendMsgBuff(b, c); }       break;      \
        case MSG_ORIGIN_SYS_TRANSFER:   { if(sysTransfer)       sysTransfer->sendMsgBuff(b, c); }       break;      \
        default: CrLogW("Unable to find the source of the message! origin = [%d]", a);                  break;      \
    }                                                                                                               \

/**
 * @description: 线程间消息命令字
 */
typedef enum {
    SYSTEM_MANAGER_CMD_MIX = 4096,

    /**
     * @description: 无应答指令
     * @param  {*}
     * @return {*}
     */    
    MANAGER_CMD_MESSAGE_TEST = 5000,
    MANAGER_SYNC_SYSTEM_CONFIG, // 同步系统配置到各管理线程
    MANAGER_SYNC_PRINT_SAVE_PARA, // 同步打印机保存参数到各管理线程
    MANAGER_CONTROL_SYSTEM_REBOOT, // 系统重启
    MANAGER_CONTROL_SYSTEM_RESET,// 系统复位
    MANAGER_SYNC_UDISK_STATE, // 同步U盘状态

    MANAGER_PUASE_GET_HOTEND_BED_TEMP, // 暂停自动获取温度数据
    MANAGER_SEND_AUDIO_MESSAGE, // 发送音频播报消息
    MANAGER_DEVICE_PRINT_FINISH, // 上报打印完成
    MANAGER_DEVICE_STATE_CHANGE, // 设备状态发生改变
    MANAGER_SYNC_DEV_UPGRADE_STATE, // 同步设备升级状态
    MANAGER_SYNC_PRINT_WORK_INFO, // 同步当前打印任务信息
    MANAGER_CMD_UPLOAD_DELAY_IMAGE, // 上传延时摄影视频

    MANAGER_CMD_AUTO_PID_RESULT_CONFIRM_REMIND, // 自动PID结果确认
    MANAGER_CMD_REPORT_AUTO_LEVEL_RESULT, // 同步自动调平结果
    MANAGER_CMD_SYNC_DELAY_IMAGE_CONFIG, // 同步延时摄影配置
    MANAGER_CMD_SYNC_TEMP_AUTO_CONFIG, // 同步延时摄影配置
    MANAGER_CMD_SYNC_MATERIAL_WARMUP_CONFIG, // 同步延时摄影配置
    MANAGER_CMD_SYNC_POWER_LOSS_CONFIG, // 同步断电续打配置
    MANAGER_CMD_SYNC_AI_CONTROL_CONFIG, // 同步AI控制配置
    MANAGER_CMD_SYNC_FILE_COPY_PROGRESS, // 同步文件拷贝进度
    MANAGER_CMD_SYNC_GCODE_DOWNLOAD, // 网络同步gcode下载状态
    MANAGER_CMD_SYNC_UPGRADE_REBOOT_INFO, // 同步升级重启信息
    MANAGER_CMD_SYNC_PRINT_OBJECT_INFO, // 同步打印对象信息

    /**
     * @description: Gcode 指令
     * @param  {*}
     * @return {*}
     */
    // 设置指令
    MANAGER_CMD_GCODE_START_PRINT_REQ = 6000,
    MANAGER_CMD_GCODE_START_PRINT_ANS,
    MANAGER_CMD_GCODE_START_CLOUD_PRINT_REQ,
    MANAGER_CMD_GCODE_START_CLOUD_PRINT_ANS,
    MANAGER_CMD_GCODE_FLUIDD_START_PRINT_REQ,
    MANAGER_CMD_GCODE_FLUIDD_START_PRINT_ANS,
    MANAGER_CMD_GCODE_PAUSE_PRINT_REQ,
    MANAGER_CMD_GCODE_PAUSE_PRINT_ANS,
    MANAGER_CMD_GCODE_RESUME_PRINT_REQ,
    MANAGER_CMD_GCODE_RESUME_PRINT_ANS,
    MANAGER_CMD_GCODE_STOP_PRINT_REQ,
    MANAGER_CMD_GCODE_STOP_PRINT_ANS,
    MANAGER_CMD_GCODE_RETURN_HOME_REQ,
    MANAGER_CMD_GCODE_RETURN_HOME_ANS,
    MANAGER_CMD_GCODE_HOTEND_XYZ_MOVE_REQ,
    MANAGER_CMD_GCODE_HOTEND_XYZ_MOVE_ANS,
    MANAGER_CMD_GCODE_OPEN_FAN_REQ,
    MANAGER_CMD_GCODE_OPEN_FAN_ANS,
    MANAGER_CMD_GCODE_STOP_FAN_REQ,
    MANAGER_CMD_GCODE_STOP_FAN_ANS,
    MANAGER_CMD_GCODE_LIGHT_VALUE_REQ,
    MANAGER_CMD_GCODE_LIGHT_VALUE_ANS,
    MANAGER_CMD_GCODE_STOP_ALL_HEAT_REQ,
    MANAGER_CMD_GCODE_STOP_ALL_HEAT_ANS,
    MANAGER_CMD_GCODE_DEVICE_AUTO_LEVEL_REQ,
    MANAGER_CMD_GCODE_DEVICE_AUTO_LEVEL_ANS,
    MANAGER_CMD_GCODE_SET_AUTO_LEVEL_POINTS_REQ,
    MANAGER_CMD_GCODE_SET_AUTO_LEVEL_POINTS_ANS,
    MANAGER_CMD_GCODE_SET_MOTOR_LOCK_REQ,
    MANAGER_CMD_GCODE_SET_MOTOR_LOCK_ANS,
    MANAGER_CMD_GCODE_SET_MOTOR_UNLOCK_REQ,
    MANAGER_CMD_GCODE_SET_MOTOR_UNLOCK_ANS,
    MANAGER_CMD_GCODE_SET_ABSOLUTE_REQ,
    MANAGER_CMD_GCODE_SET_ABSOLUTE_ANS,
    MANAGER_CMD_GCODE_SET_RELATIVE_REQ,
    MANAGER_CMD_GCODE_SET_RELATIVE_ANS,
    MANAGER_CMD_GCODE_SET_DEVICE_RESET_REQ,
    MANAGER_CMD_GCODE_SET_DEVICE_RESET_ANS,
    MANAGER_CMD_GCODE_SET_STOP_HEATING_REQ,
    MANAGER_CMD_GCODE_SET_STOP_HEATING_ANS,
    MANAGER_CMD_GCODE_SET_AXIS_RECOUP_REQ,
    MANAGER_CMD_GCODE_SET_AXIS_RECOUP_ANS,
    MANAGER_CMD_GCODE_SET_NOZZLE_TEMP_REQ,
    MANAGER_CMD_GCODE_SET_NOZZLE_TEMP_ANS,
    MANAGER_CMD_GCODE_SET_BED_TEMP_REQ,
    MANAGER_CMD_GCODE_SET_BED_TEMP_ANS,
    MANAGER_CMD_GCODE_SET_HOTEND_PID_REQ,
    MANAGER_CMD_GCODE_SET_HOTEND_PID_ANS,
    MANAGER_CMD_GCODE_SET_BED_PID_REQ,
    MANAGER_CMD_GCODE_SET_BED_PID_ANS,
    MANAGER_CMD_GCODE_SET_PRINT_SPEED_REQ,
    MANAGER_CMD_GCODE_SET_PRINT_SPEED_ANS,
    MANAGER_CMD_GCODE_SET_PRINT_FLOW_REQ,
    MANAGER_CMD_GCODE_SET_PRINT_FLOW_ANS,
    MANAGER_CMD_GCODE_SET_STEP_VALUE_REQ,
    MANAGER_CMD_GCODE_SET_STEP_VALUE_ANS,
    MANAGER_CMD_GCODE_SET_MAX_ACCELERATION_REQ,
    MANAGER_CMD_GCODE_SET_MAX_ACCELERATION_ANS,
    MANAGER_CMD_GCODE_SET_MAX_SPEED_REQ,
    MANAGER_CMD_GCODE_SET_MAX_SPEED_ANS,
    MANAGER_CMD_GCODE_SET_MAX_JERK_REQ,
    MANAGER_CMD_GCODE_SET_MAX_JERK_ANS,
    MANAGER_CMD_GCODE_SET_MAX_CORNER_REQ,
    MANAGER_CMD_GCODE_SET_MAX_CORNER_ANS,
    MANAGER_CMD_GCODE_SET_PRESSURE_ADVANCE_REQ,
    MANAGER_CMD_GCODE_SET_PRESSURE_ADVANCE_ANS,
    MANAGER_CMD_GCODE_SET_SMOOTH_TIME_REQ,
    MANAGER_CMD_GCODE_SET_SMOOTH_TIME_ANS,
    MANAGER_CMD_GCODE_SET_MATERIAL_DELECT_REQ,
    MANAGER_CMD_GCODE_SET_MATERIAL_DELECT_ANS,
    MANAGER_CMD_GCODE_SET_POWER_LOSS_SW_REQ,
    MANAGER_CMD_GCODE_SET_POWER_LOSS_SW_ANS,
    MANAGER_CMD_GCODE_SET_CR_TOUCH_REQ,
    MANAGER_CMD_GCODE_SET_CR_TOUCH_ANS,
    MANAGER_CMD_GCODE_SET_HOME_OFFSET_REQ,
    MANAGER_CMD_GCODE_SET_HOME_OFFSET_ANS,
    MANAGER_CMD_GCODE_SET_SAVE_CONFIG_REQ,
    MANAGER_CMD_GCODE_SET_SAVE_CONFIG_ANS,
    MANAGER_CMD_GCODE_SET_INSERT_FILAMENT_REQ,
    MANAGER_CMD_GCODE_SET_INSERT_FILAMENT_ANS,
    MANAGER_CMD_GCODE_SET_GCODE_MACRO_REQ,
    MANAGER_CMD_GCODE_SET_GCODE_MACRO_ANS,
    MANAGER_CMD_GCODE_SET_CONSOLE_CTL_REQ,
    MANAGER_CMD_GCODE_SET_CONSOLE_CTL_ANS,
    MANAGER_CMD_GCODE_SET_RESTART_KLIPPER_REQ,
    MANAGER_CMD_GCODE_SET_RESTART_KLIPPER_ANS,
    MANAGER_CMD_GCODE_SET_FIRMWARE_RESTART_REQ,
    MANAGER_CMD_GCODE_SET_FIRMWARE_RESTART_ANS,
    MANAGER_CMD_GCODE_SET_RESONANCE_TEST_REQ,
    MANAGER_CMD_GCODE_SET_RESONANCE_TEST_ANS,
    MANAGER_CMD_GCODE_SET_QUIET_MODE_REQ,
    MANAGER_CMD_GCODE_SET_QUIET_MODE_ANS,
    MANAGER_CMD_GCODE_SET_LOAD_MATERIAL_REQ,
    MANAGER_CMD_GCODE_SET_LOAD_MATERIAL_ANS,
    MANAGER_CMD_GCODE_SET_QUIT_MATERIAL_REQ,
    MANAGER_CMD_GCODE_SET_QUIT_MATERIAL_ANS,
    MANAGER_CMD_GCODE_SET_LASER_CALIBRATION_REQ,
    MANAGER_CMD_GCODE_SET_LASER_CALIBRATION_ANS,
    MANAGER_CMD_GCODE_SET_END_PRINT_POINT_REQ,
    MANAGER_CMD_GCODE_SET_END_PRINT_POINT_ANS,
    MANAGER_CMD_GCODE_SET_EXCLUDE_OBJECT_REQ,
    MANAGER_CMD_GCODE_SET_EXCLUDE_OBJECT_ANS,
    MANAGER_CMD_GCODE_SET_MESH_INFO_REQ,
    MANAGER_CMD_GCODE_SET_MESH_INFO_ANS,
    // 获取指令
    MANAGER_CMD_GCODE_GET_SD_FILE_REQ,
    MANAGER_CMD_GCODE_GET_SD_FILE_ANS,
    MANAGER_CMD_GCODE_GET_SD_MODEL_IMAGE_REQ,
    MANAGER_CMD_GCODE_GET_SD_MODEL_IMAGE_ANS,
    MANAGER_CMD_GCODE_GET_SD_GCODE_PHOTO_REQ,
    MANAGER_CMD_GCODE_GET_SD_GCODE_PHOTO_ANS,
    MANAGER_CMD_GCODE_GET_HOTEND_XYZ_LOCAL_REQ,
    MANAGER_CMD_GCODE_GET_HOTEND_XYZ_LOCAL_ANS,
    MANAGER_CMD_GCODE_GET_SD_FILE_LIST_ANS,
    MANAGER_CMD_GET_GSENSOR_EXIST_REQ,
    MANAGER_CMD_GET_GSENSOR_EXIST_ANS,

    MANAGER_CMD_START_LASER_TEST_REQ,
    MANAGER_CMD_START_LASER_TEST_ANS,
    /**
     * @description: 通用指令
     * @param  {*}
     * @return {*}
     */    
    MANAGER_CMD_START_POWER_LOSS_REQ = 6500,
    MANAGER_CMD_START_POWER_LOSS_ANS,
    MANAGER_CMD_CANCEL_POWER_LOSS_REQ,
    MANAGER_CMD_CANCEL_POWER_LOSS_ANS,
    MANAGER_CMD_START_MATERIAL_WARM_UP_REQ,
    MANAGER_CMD_START_MATERIAL_WARM_UP_ANS,
    MANAGER_CMD_START_TEMP_AUTO_PID_REQ,
    MANAGER_CMD_START_TEMP_AUTO_PID_ANS,
    MANAGER_CMD_GET_UPGRADE_INFO_REQ,
    MANAGER_CMD_GET_UPGRADE_INFO_ANS,
    MANAGER_CMD_START_UPGRADE_REQ,
    MANAGER_CMD_START_UPGRADE_ANS,
    MANAGER_CMD_CANCEL_UPGRADE_REQ,
    MANAGER_CMD_CANCEL_UPGRADE_ANS,
    MANAGER_CMD_SYSTEM_RESET_REQ,
    MANAGER_CMD_SYSTEM_RESET_ANS,
    MANAGER_CMD_GET_POWER_LOSS_INFO_REQ,
    MANAGER_CMD_GET_POWER_LOSS_INFO_ANS,
    MANAGER_CMD_GET_CUR_MCU_VERSION_REQ,
    MANAGER_CMD_GET_CUR_MCU_VERSION_ANS,
    MANAGER_CMD_UPLOAD_LOCAL_VIDEO_REQ,
    MANAGER_CMD_UPLOAD_LOCAL_VIDEO_ANS,
    MANAGER_CMD_UPLOAD_LOCAL_LOG_REQ,
    MANAGER_CMD_UPLOAD_LOCAL_LOG_ANS,    
    MANAGER_CMD_UPDATE_USER_CXY_INFO_REQ,
    MANAGER_CMD_UPDATE_USER_CXY_INFO_ANS,
    MANAGER_CMD_SYSTEM_RESET_TO_APP_REQ,
    MANAGER_CMD_SYSTEM_RESET_TO_APP_ANS,

    /**
     * @description: wifi交互指令
     * @param  {*}
     * @return {*}
     */    
    MANAGER_CMD_WIFI_USER_SCAN_WIFI_REQ = 8100,
    MANAGER_CMD_WIFI_USER_SCAN_WIFI_ANS,
    MANAGER_CMD_WIFI_USER_CONNECT_NETWORK_REQ,
    MANAGER_CMD_WIFI_USER_CONNECT_NETWORK_ANS,
    MANAGER_CMD_WIFI_USER_CONNECT_SAVE_NETWORK_REQ,
    MANAGER_CMD_WIFI_USER_CONNECT_SAVE_NETWORK_ANS,
    MANAGER_CMD_WIFI_USER_GET_WIFI_INFO_REQ,
    MANAGER_CMD_WIFI_USER_GET_WIFI_INFO_ANS,
    MANAGER_CMD_WIFI_USER_DISCONNECT_NETWORK_REQ,
    MANAGER_CMD_WIFI_USER_DISCONNECT_NETWORK_ANS,
    MANAGER_CMD_WIFI_USER_REMOVE_NETWORK_REQ,
    MANAGER_CMD_WIFI_USER_REMOVE_NETWORK_ANS,
}MsgCmd;

typedef enum {
    BUTTON_SOUND_TECHNOLOGY = 1,
    BUTTON_SOUND_SMART,
    BUTTON_SOUND_SHORT,
    BUTTON_SOUND_CRISP,
}ButtomSoundeFfect_t;

typedef enum {
    AUDIO_BUTTON_BEEP = 1,
    AUDIO_START_PRINT = 2,
}AudioPlayNum_t;

#ifdef  __cplusplus  
}  
#endif  /* end of __cplusplus */  

#endif
