/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SystemServer.proto */

#ifndef PROTOBUF_C_SystemServer_2eproto__INCLUDED
#define PROTOBUF_C_SystemServer_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ServerTest ServerTest;
typedef struct _GeneralRes GeneralRes;
typedef struct _SendString SendString;
typedef struct _MaterialPrefer MaterialPrefer;
typedef struct _MaterialPreferList MaterialPreferList;
typedef struct _TempAutoPidPrefer TempAutoPidPrefer;
typedef struct _TempAutoPidPreferList TempAutoPidPreferList;
typedef struct _DelayImagePrefer DelayImagePrefer;
typedef struct _PowerLossPrefer PowerLossPrefer;
typedef struct _AiControlPrefer AiControlPrefer;
typedef struct _WifiInfo WifiInfo;
typedef struct _NetworksInfo NetworksInfo;
typedef struct _SystemConfigProto SystemConfigProto;
typedef struct _AxisPositionInfo AxisPositionInfo;
typedef struct _PidInfo PidInfo;
typedef struct _Extruder Extruder;
typedef struct _HeaterBed HeaterBed;
typedef struct _MultiFan MultiFan;
typedef struct _MultiGsensor MultiGsensor;
typedef struct _PrintWorkInfo PrintWorkInfo;
typedef struct _PrintSavePara PrintSavePara;
typedef struct _SyncPrintState SyncPrintState;
typedef struct _AppControlPrint AppControlPrint;
typedef struct _GetGcodeFIleList GetGcodeFIleList;
typedef struct _LocalGcodeInfo LocalGcodeInfo;
typedef struct _SystemSetting SystemSetting;
typedef struct _LoadQuitMaterial LoadQuitMaterial;
typedef struct _DisControlPrint DisControlPrint;
typedef struct _AutoPidResult AutoPidResult;
typedef struct _ReportAutoLevelRes ReportAutoLevelRes;
typedef struct _UpgradeInfo UpgradeInfo;
typedef struct _UpgradeInfoList UpgradeInfoList;
typedef struct _HistoryRecord HistoryRecord;
typedef struct _HistoryRecordList HistoryRecordList;
typedef struct _DelayImageInfo DelayImageInfo;
typedef struct _DelayImageInfoList DelayImageInfoList;
typedef struct _MutableTypeData MutableTypeData;
typedef struct _UpdataErrorInfo UpdataErrorInfo;
typedef struct _MultipleBedTemp MultipleBedTemp;
typedef struct _WebControlPrint WebControlPrint;
typedef struct _FileControl FileControl;
typedef struct _DownloadGcode DownloadGcode;
typedef struct _UpgradeRebootSync UpgradeRebootSync;
typedef struct _ExportLogState ExportLogState;


/* --- enums --- */


/* --- messages --- */

struct  _ServerTest
{
  ProtobufCMessage base;
  char *dialogue;
};
#define SERVER_TEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_test__descriptor) \
    , NULL }


/*
 * 消息通用回复
 */
struct  _GeneralRes
{
  ProtobufCMessage base;
  /*
   * 响应结果
   */
  uint32_t result;
};
#define GENERAL_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&general_res__descriptor) \
    , 0 }


/*
 * 传输字符串
 */
struct  _SendString
{
  ProtobufCMessage base;
  /*
   * 字符串
   */
  ProtobufCBinaryData str;
};
#define SEND_STRING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&send_string__descriptor) \
    , {0,NULL} }


/*
 * 显示屏设置打印材料偏好
 */
struct  _MaterialPrefer
{
  ProtobufCMessage base;
  int32_t id;
  protobuf_c_boolean has_name;
  ProtobufCBinaryData name;
  protobuf_c_boolean has_hotendtemp;
  int32_t hotendtemp;
  protobuf_c_boolean has_bedtemp;
  int32_t bedtemp;
};
#define MATERIAL_PREFER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&material_prefer__descriptor) \
    , 0, 0,{0,NULL}, 0,0, 0,0 }


/*
 * 打印材料偏好列表
 */
struct  _MaterialPreferList
{
  ProtobufCMessage base;
  size_t n_list;
  MaterialPrefer **list;
};
#define MATERIAL_PREFER_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&material_prefer_list__descriptor) \
    , 0,NULL }


/*
 * 温度自动pid偏好
 */
struct  _TempAutoPidPrefer
{
  ProtobufCMessage base;
  int32_t id;
  protobuf_c_boolean has_name;
  ProtobufCBinaryData name;
  protobuf_c_boolean has_temp;
  int32_t temp;
  protobuf_c_boolean has_time;
  int32_t time;
};
#define TEMP_AUTO_PID_PREFER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temp_auto_pid_prefer__descriptor) \
    , 0, 0,{0,NULL}, 0,0, 0,0 }


/*
 * 温度自动pid偏好列表
 */
struct  _TempAutoPidPreferList
{
  ProtobufCMessage base;
  size_t n_list;
  TempAutoPidPrefer **list;
};
#define TEMP_AUTO_PID_PREFER_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temp_auto_pid_prefer_list__descriptor) \
    , 0,NULL }


/*
 * 延时摄影偏好
 */
struct  _DelayImagePrefer
{
  ProtobufCMessage base;
  protobuf_c_boolean has_sw;
  int32_t sw;
  protobuf_c_boolean has_location;
  int32_t location;
  protobuf_c_boolean has_frame;
  int32_t frame;
  protobuf_c_boolean has_interval;
  int32_t interval;
  protobuf_c_boolean has_mintime;
  int32_t mintime;
};
#define DELAY_IMAGE_PREFER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&delay_image_prefer__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0 }


/*
 * 断电续打偏好
 */
struct  _PowerLossPrefer
{
  ProtobufCMessage base;
  protobuf_c_boolean has_sw;
  int32_t sw;
};
#define POWER_LOSS_PREFER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&power_loss_prefer__descriptor) \
    , 0,0 }


/*
 * AI控制偏好
 */
struct  _AiControlPrefer
{
  ProtobufCMessage base;
  /*
   * 开关
   */
  protobuf_c_boolean has_sw;
  int32_t sw;
  /*
   * 故障检测
   */
  protobuf_c_boolean has_detection;
  int32_t detection;
  /*
   * 故障暂停打印
   */
  protobuf_c_boolean has_pauseprint;
  int32_t pauseprint;
  /*
   * 首层检测
   */
  protobuf_c_boolean has_firstfloor;
  int32_t firstfloor;
  /*
   * 意面检测时间
   */
  protobuf_c_boolean has_pastatime;
  int32_t pastatime;
  /*
   * 意面可信度，真实值
   */
  protobuf_c_boolean has_pastatruth;
  float pastatruth;
  /*
   * AI数据采集
   */
  protobuf_c_boolean has_datacollect;
  int32_t datacollect;
  /*
   * 异物可信度，真实值
   */
  protobuf_c_boolean has_sundriestruth;
  float sundriestruth;
  /*
   * 流量检测
   */
  protobuf_c_boolean has_flowdetect;
  int32_t flowdetect;
  /*
   * AI检测，摄像头最佳高度（mm）
   */
  protobuf_c_boolean has_optimalheight;
  int32_t optimalheight;
  /*
   * AI模式，不同模式可能涉及不同检测时间、不同置信度
   */
  protobuf_c_boolean has_aimode;
  int32_t aimode;
};
#define AI_CONTROL_PREFER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ai_control_prefer__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0 }


/*
 * WiFi信息
 */
struct  _WifiInfo
{
  ProtobufCMessage base;
  /*
   * bssid
   */
  protobuf_c_boolean has_bssid;
  ProtobufCBinaryData bssid;
  /*
   * 工作频率
   */
  protobuf_c_boolean has_frequer;
  ProtobufCBinaryData frequer;
  /*
   * 信号强度
   */
  protobuf_c_boolean has_signal;
  ProtobufCBinaryData signal;
  /*
   * 标志位
   */
  protobuf_c_boolean has_flags;
  ProtobufCBinaryData flags;
  /*
   * ssid
   */
  protobuf_c_boolean has_ssid;
  ProtobufCBinaryData ssid;
  /*
   * WiFi是否保存
   */
  protobuf_c_boolean has_wifiusage;
  uint32_t wifiusage;
  /*
   * 是否加密
   */
  protobuf_c_boolean has_encrypt;
  uint32_t encrypt;
};
#define WIFI_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wifi_info__descriptor) \
    , 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0 }


/*
 * 获取WiFi信息
 */
struct  _NetworksInfo
{
  ProtobufCMessage base;
  /*
   * 热点状态
   */
  protobuf_c_boolean has_status;
  uint32_t status;
  /*
   * ip地址
   */
  protobuf_c_boolean has_ip;
  ProtobufCBinaryData ip;
  /*
   * 名称
   */
  protobuf_c_boolean has_ssid;
  ProtobufCBinaryData ssid;
  /*
   * 密码
   */
  protobuf_c_boolean has_pass;
  ProtobufCBinaryData pass;
  /*
   * 信号强度
   */
  protobuf_c_boolean has_signal;
  int32_t signal;
  /*
   * 扫描热点列表
   */
  size_t n_list;
  WifiInfo **list;
};
#define NETWORKS_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&networks_info__descriptor) \
    , 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,NULL }


/*
 * 系统配置信息
 */
struct  _SystemConfigProto
{
  ProtobufCMessage base;
  /*
   * 系统版本
   */
  protobuf_c_boolean has_sys_version;
  ProtobufCBinaryData sys_version;
  /*
   * 固件版本
   */
  protobuf_c_boolean has_fw_version;
  ProtobufCBinaryData fw_version;
  /*
   * 硬件版本
   */
  protobuf_c_boolean has_hw_version;
  ProtobufCBinaryData hw_version;
  /*
   * 下位机硬件版本
   */
  protobuf_c_boolean has_hw1_version;
  ProtobufCBinaryData hw1_version;
  /*
   * 官方网址
   */
  protobuf_c_boolean has_website;
  ProtobufCBinaryData website;
  /*
   * 设备型号
   */
  protobuf_c_boolean has_model;
  int32_t model;
  /*
   * 型号字符
   */
  protobuf_c_boolean has_model_str;
  ProtobufCBinaryData model_str;
  /*
   * 热床长度
   */
  protobuf_c_boolean has_bed_length;
  int32_t bed_length;
  /*
   * 热床宽度
   */
  protobuf_c_boolean has_bed_width;
  int32_t bed_width;
  /*
   * 热床高度
   */
  protobuf_c_boolean has_bed_hight;
  int32_t bed_hight;
  /*
   * 通信数据交换方式
   */
  protobuf_c_boolean has_swap_way;
  int32_t swap_way;
  /*
   * 客户ID
   */
  protobuf_c_boolean has_customer;
  int32_t customer;
  /*
   * 语言类型
   */
  protobuf_c_boolean has_language;
  int32_t language;
  /*
   * 音量大小
   */
  protobuf_c_boolean has_sound_size;
  int32_t sound_size;
  /*
   * 音频开关
   */
  protobuf_c_boolean has_sound_sw;
  int32_t sound_sw;
  /*
   * 灯光开关
   */
  protobuf_c_boolean has_light_sw;
  int32_t light_sw;
  /*
   * wifi开关
   */
  protobuf_c_boolean has_wifi_sw;
  int32_t wifi_sw;
  /*
   * 主题模式
   */
  protobuf_c_boolean has_theme_mode;
  int32_t theme_mode;
  /*
   * 开机自检开关
   */
  protobuf_c_boolean has_self_test_sw;
  int32_t self_test_sw;
  /*
   * 屏保开启时间
   */
  protobuf_c_boolean has_screensaver;
  int32_t screensaver;
  /*
   * 屏幕亮度值
   */
  protobuf_c_boolean has_screen_value;
  int32_t screen_value;
  /*
   * 自动关机
   */
  protobuf_c_boolean has_auto_power_off;
  int32_t auto_power_off;
  /*
   * 横竖屏方向
   */
  protobuf_c_boolean has_ui_direction;
  int32_t ui_direction;
  /*
   * 设备SN
   */
  protobuf_c_boolean has_device_sn;
  ProtobufCBinaryData device_sn;
  /*
   * 设备MAC
   */
  protobuf_c_boolean has_device_mac;
  ProtobufCBinaryData device_mac;
  /*
   * 累计使用总时间
   */
  protobuf_c_boolean has_total_time;
  uint32_t total_time;
  /*
   * 部署设置
   */
  protobuf_c_boolean has_deploy_setting;
  int32_t deploy_setting;
  /*
   * 音效设置
   */
  protobuf_c_boolean has_sounde_ffect;
  int32_t sounde_ffect;
  /*
   * 全屏模式
   */
  protobuf_c_boolean has_full_screen;
  int32_t full_screen;
  /*
   * 灯光亮度
   */
  protobuf_c_boolean has_light_value;
  int32_t light_value;
  /*
   * Z轴方向
   */
  protobuf_c_boolean has_z_direction;
  int32_t z_direction;
  /*
   * 打印前检测开关
   */
  protobuf_c_boolean has_enableselftest;
  int32_t enableselftest;
  /*
   * 时区设置
   */
  protobuf_c_boolean has_time_zone;
  ProtobufCBinaryData time_zone;
  /*
   * 服务器配置 {1：正式，2：预发布，3：测试，4：联调}
   */
  protobuf_c_boolean has_server_config;
  int32_t server_config;
  /*
   * 升级提醒
   */
  protobuf_c_boolean has_upgrade_remind;
  int32_t upgrade_remind;
  /*
   * 服务器位置 {1：国内，2：海外}
   */
  protobuf_c_boolean has_server_local;
  int32_t server_local;
  /*
   * 同意隐私协议
   */
  protobuf_c_boolean has_agree_privacy;
  int32_t agree_privacy;
  /*
   * 权限标志
   */
  protobuf_c_boolean has_creality_num;
  int32_t creality_num;
  /*
   * 主机名称
   */
  protobuf_c_boolean has_host_name;
  ProtobufCBinaryData host_name;
  /*
   * 用户数据采集
   */
  protobuf_c_boolean has_data_collect;
  int32_t data_collect;
};
#define SYSTEM_CONFIG_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system_config_proto__descriptor) \
    , 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,{0,NULL}, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,{0,NULL}, 0,0, 0,0, 0,0, 0,0, 0,0, 0,{0,NULL}, 0,0 }


/*
 * 轴位置信息
 */
struct  _AxisPositionInfo
{
  ProtobufCMessage base;
  /*
   * x轴
   */
  int32_t x;
  /*
   * y轴
   */
  int32_t y;
  /*
   * z轴
   */
  int32_t z;
  /*
   * e轴
   */
  int32_t e;
};
#define AXIS_POSITION_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&axis_position_info__descriptor) \
    , 0, 0, 0, 0 }


/*
 * PID信息
 */
struct  _PidInfo
{
  ProtobufCMessage base;
  /*
   * p值
   */
  int32_t p;
  /*
   * i值
   */
  int32_t i;
  /*
   * d值
   */
  int32_t d;
};
#define PID_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pid_info__descriptor) \
    , 0, 0, 0 }


/*
 * 多喷嘴
 */
struct  _Extruder
{
  ProtobufCMessage base;
  /*
   * 喷嘴
   */
  protobuf_c_boolean has_extruder;
  int32_t extruder;
};
#define EXTRUDER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&extruder__descriptor) \
    , 0,0 }


/*
 * 多热床
 */
struct  _HeaterBed
{
  ProtobufCMessage base;
  /*
   * 热床
   */
  protobuf_c_boolean has_heater_bed;
  int32_t heater_bed;
  /*
   * 
   */
  protobuf_c_boolean has_heater_bed_0;
  int32_t heater_bed_0;
  /*
   * 
   */
  protobuf_c_boolean has_heater_bed_1;
  int32_t heater_bed_1;
  /*
   * 
   */
  protobuf_c_boolean has_heater_bed_2;
  int32_t heater_bed_2;
};
#define HEATER_BED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&heater_bed__descriptor) \
    , 0,0, 0,0, 0,0, 0,0 }


/*
 * 多风扇
 */
struct  _MultiFan
{
  ProtobufCMessage base;
  /*
   * 风扇
   */
  protobuf_c_boolean has_multi_fan_model;
  int32_t multi_fan_model;
  /*
   * 
   */
  protobuf_c_boolean has_multi_fan_case;
  int32_t multi_fan_case;
  /*
   * 
   */
  protobuf_c_boolean has_multi_fan_auxiliary;
  int32_t multi_fan_auxiliary;
};
#define MULTI_FAN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&multi_fan__descriptor) \
    , 0,0, 0,0, 0,0 }


/*
 * 多个Gsensor
 */
struct  _MultiGsensor
{
  ProtobufCMessage base;
  /*
   * Gsensor
   */
  protobuf_c_boolean has_multi_gsensor_all;
  protobuf_c_boolean multi_gsensor_all;
  /*
   */
  protobuf_c_boolean has_multi_gsensor_x;
  protobuf_c_boolean multi_gsensor_x;
  /*
   * 
   */
  protobuf_c_boolean has_multi_gsensor_y;
  protobuf_c_boolean multi_gsensor_y;
};
#define MULTI_GSENSOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&multi_gsensor__descriptor) \
    , 0,0, 0,0, 0,0 }


/*
 * 当前打印任务信息
 */
struct  _PrintWorkInfo
{
  ProtobufCMessage base;
  /*
   * 打印任务ID
   */
  int32_t id;
  /*
   * 打印文件名称
   */
  ProtobufCBinaryData filename;
  /*
   * 文件大小
   */
  int32_t size;
  /*
   * 创建时间
   */
  int32_t ctime;
  /*
   * 打印开始时间
   */
  int32_t starttime;
  /*
   * 预计使用时间
   */
  int32_t totaltime;
  /*
   * 预计耗材
   */
  uint32_t consumables;
  /*
   * 启动打印方式（UI、APP、...）
   */
  int32_t startway;
  /*
   * 缩略图路径
   */
  ProtobufCBinaryData thumbnail;
  /*
   * 注水图路径
   */
  ProtobufCBinaryData photo;
  /*
   * 注水图起始像素点
   */
  uint32_t startpixel;
  /*
   * 注水图结束像素点
   */
  uint32_t endpixel;
  /*
   * 注水图模型高度
   */
  uint32_t modelheight;
  /*
   * 注水图模型层高
   */
  uint32_t layerheight;
  /*
   * 切片软件
   */
  ProtobufCBinaryData software;
};
#define PRINT_WORK_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&print_work_info__descriptor) \
    , 0, {0,NULL}, 0, 0, 0, 0, 0, 0, {0,NULL}, {0,NULL}, 0, 0, 0, 0, {0,NULL} }


/*
 * 打印机保存参数
 */
struct  _PrintSavePara
{
  ProtobufCMessage base;
  /*
   * 断电续打开关
   */
  int32_t powerloss;
  /*
   * 断料检测
   */
  int32_t materialdetect;
  /*
   * 喷嘴温度PID
   */
  PidInfo *hotendpid;
  /*
   * 热床温度PID
   */
  PidInfo *bedpid;
  /*
   * 自动调平值
   */
  size_t n_levelvalue;
  int32_t *levelvalue;
  /*
   * 原点偏移
   */
  AxisPositionInfo *homeoffset;
  /*
   * 轴补偿值
   */
  AxisPositionInfo *axisrecoup;
  /*
   * 步进值
   */
  AxisPositionInfo *stepvalue;
  /*
   * 最大加速度
   */
  AxisPositionInfo *acceleration;
  /*
   * 最大速度
   */
  AxisPositionInfo *speed;
  /*
   * 最大抖动速度
   */
  AxisPositionInfo *jerk;
  /*
   * 自动调平点数
   */
  AxisPositionInfo *levelpoint;
  /*
   * gcode宏定义
   */
  size_t n_gcodemacro;
  ProtobufCBinaryData *gcodemacro;
  /*
   * 高速最大速度
   */
  uint32_t k_speed;
  /*
   * 高速最大加速度
   */
  uint32_t k_acceleration;
  /*
   * 高速最大拐角速度
   */
  uint32_t k_corner;
  /*
   * 高速最大加速到减速的加速度限制
   */
  uint32_t k_jerk;
  /*
   * 高速压力推进
   */
  uint32_t pressureadvance;
  /*
   * 高速平滑时间
   */
  uint32_t smoothtime;
  /*
   * 风扇反馈
   */
  uint32_t fanfeedback;
  /*
   * 喷嘴硬件最大温度
   */
  uint32_t nozzlehwmaxtemp;
  /*
   * 热床硬件最大温度
   */
  uint32_t bedhwmaxtemp;
  /*
   * 设备最大尺寸
   */
  AxisPositionInfo *devmaxsize;
  /*
   * 设备最小尺寸
   */
  AxisPositionInfo *devminsize;
  /*
   * 热床调平信息
   */
  ProtobufCBinaryData bedmeshinfo;
};
#define PRINT_SAVE_PARA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&print_save_para__descriptor) \
    , 0, 0, NULL, NULL, 0,NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0,NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, {0,NULL} }


/*
 * 同步打印机状态到网络或其他人机交互服务
 */
struct  _SyncPrintState
{
  ProtobufCMessage base;
  /*
   * 串口连接成功标志
   */
  int32_t serialport;
  /*
   * 串口连接成功标志
   */
  int32_t sdcardexists;
  /*
   * 工作模式
   */
  int32_t workmode;
  /*
   * 工作状态
   */
  int32_t workstate;
  /*
   * 风扇状态
   */
  size_t n_fanstate;
  int32_t *fanstate;
  /*
   * 灯光状态
   */
  int32_t lightstate;
  /*
   * wifi状态
   */
  int32_t wifistate;
  /*
   * 打印速度
   */
  int32_t printspeed;
  /*
   * 打印层数
   */
  int32_t curprintlayer;
  /*
   * 打印进度
   */
  int32_t printprogress;
  /*
   * 当前喷嘴温度
   */
  size_t n_curhotendtemp;
  int32_t *curhotendtemp;
  /*
   * 当前热床温度
   */
  size_t n_curbedtemp;
  int32_t *curbedtemp;
  /*
   * 喷嘴目标温度
   */
  size_t n_targethotendtemp;
  int32_t *targethotendtemp;
  /*
   * 热床目标温度
   */
  size_t n_targetbedtemp;
  int32_t *targetbedtemp;
  /*
   * 打印使用时间
   */
  int32_t printusagetime;
  /*
   * 打印剩余时间
   */
  int32_t printremaintime;
  /*
   * 自动调平进度
   */
  int32_t autolevelprogress;
  /*
   * 自动PID进度
   */
  int32_t autopidprogress;
  /*
   * 调平模块状态 
   */
  int32_t crtouchstate;
  /*
   * 暂停状态
   */
  int32_t pausestatus;
  /*
   * 断料检测状态
   */
  size_t n_materialstatus;
  int32_t *materialstatus;
  /*
   * 异常错误码
   */
  UpdataErrorInfo *faultcode;
  /*
   * 电机状态
   */
  int32_t motorstate;
  /*
   * 是否存在断电续打
   */
  int32_t existoffcontinue;
  /*
   * 喷嘴当前位置
   */
  AxisPositionInfo *liveposition;
  /*
   * 打印流量
   */
  int32_t printflow;
  /*
   * 轴归位状态
   */
  AxisPositionInfo *homedaxes;
  /*
   * klipper状态
   */
  int32_t klipperstata;
  /*
   * 打印使用耗材
   */
  int32_t filamentused;
  /*
   * 打印总层数
   */
  int32_t printtotallayer;
  /*
   * 喷嘴目标位置
   */
  AxisPositionInfo *gcodeposition;
  /*
   * U盘挂载状态
   */
  size_t n_udiskmount;
  int32_t *udiskmount;
  /*
   * 以太网状态
   */
  int32_t ethernetexists;
  /*
   * 摄像头状态
   */
  size_t n_cameraonline;
  int32_t *cameraonline;
  /*
   * 其他当前温度
   */
  size_t n_othercurtemp;
  int32_t *othercurtemp;
  /*
   * 当前喷嘴功率
   */
  size_t n_curhotendpower;
  int32_t *curhotendpower;
  /*
   * 当前热床功率
   */
  size_t n_curbedpower;
  int32_t *curbedpower;
  /*
   * 打印实时速度
   */
  int32_t realtimespeed;
  /*
   * 打印实时流量
   */
  int32_t realtimeflow;
  /*
   * klipper打印状态
   */
  int32_t klipperprint;
  /*
   * 虚拟SD卡路径
   */
  ProtobufCBinaryData sdpath;
  /*
   * U盘路径
   */
  ProtobufCBinaryData udiskpath;
  /*
   * 静音模式
   */
  int32_t qmodeflag;
  /*
   * 打印前校准步骤
   */
  int32_t withselftest;
  /*
   * 进料状态
   */
  int32_t loadmaterial;
  /*
   * 退料状态
   */
  int32_t quitmaterial;
  /*
   * 风扇速度
   */
  size_t n_fanspeed;
  int32_t *fanspeed;
  /*
   * 风扇百分比
   */
  size_t n_fanpercentage;
  int32_t *fanpercentage;
  /*
   * 激光模组状态
   */
  int32_t laserexists;
  /*
   * 喷嘴加热等待
   */
  int32_t nozzletempwait;
  /*
   * 热床加热等待
   */
  int32_t bedtempwait;
  /*
   * 设备状态
   */
  int32_t devicestate;
  /*
   * 扫码枪状态
   */
  int32_t scannerexists;
  /*
   * 创想云MQTT状态
   */
  int32_t cxymqttstate;
  /*
   * 日志导出、上传进度
   */
  int32_t logprogress;
  /*
   * 扫描文件进度
   */
  int32_t scanfileprogress;
};
#define SYNC_PRINT_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sync_print_state__descriptor) \
    , 0, 0, 0, 0, 0,NULL, 0, 0, 0, 0, 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0, 0, 0, 0, 0, 0, 0,NULL, NULL, 0, 0, NULL, 0, NULL, 0, 0, 0, NULL, 0,NULL, 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0, 0, 0, {0,NULL}, {0,NULL}, 0, 0, 0, 0, 0,NULL, 0,NULL, 0, 0, 0, 0, 0, 0, 0, 0 }


/*
 * 网络控制打印机
 */
struct  _AppControlPrint
{
  ProtobufCMessage base;
  /*
   * 控制执行结果
   */
  protobuf_c_boolean has_result;
  int32_t result;
  /*
   * 开启云打印
   */
  protobuf_c_boolean has_print;
  ProtobufCBinaryData print;
  /*
   * 打印控制（暂停、恢复）
   */
  protobuf_c_boolean has_pause;
  int32_t pause;
  /*
   * 打印控制（停止）
   */
  protobuf_c_boolean has_stop;
  int32_t stop;
  /*
   * 设置喷嘴目标温度
   */
  Extruder *nozzletemp;
  /*
   * 设置热床目标温度
   */
  HeaterBed *bedtemp;
  /*
   * 风扇控制
   */
  MultiFan *fan;
  /*
   * 断电续打控制
   */
  protobuf_c_boolean has_powerloss;
  int32_t powerloss;
  /*
   * 控制回原点
   */
  protobuf_c_boolean has_autohome;
  int32_t autohome;
  /*
   * 本地打印 
   */
  protobuf_c_boolean has_opgcodefile;
  ProtobufCBinaryData opgcodefile;
  /*
   * 轴移动（X\Y\Z\E）
   */
  protobuf_c_boolean has_setposition;
  ProtobufCBinaryData setposition;
  /*
   * 设置打印倍速
   */
  protobuf_c_boolean has_setfeedratepct;
  ProtobufCBinaryData setfeedratepct;
  /*
   * 设置流量倍速
   */
  protobuf_c_boolean has_setflowratepct;
  ProtobufCBinaryData setflowratepct;
  /*
   * 执行gcode宏定义
   */
  protobuf_c_boolean has_gcodecmd;
  ProtobufCBinaryData gcodecmd;
  /*
   * 延时摄影开关
   */
  protobuf_c_boolean has_videoelapse;
  int32_t videoelapse;
  /*
   * 延时摄影移开喷嘴
   */
  protobuf_c_boolean has_nozzlemovesnapshot;
  int32_t nozzlemovesnapshot;
  /*
   * 断电续打参数
   */
  protobuf_c_boolean has_powerlossswitch;
  int32_t powerlossswitch;
  /*
   * AI控制参数
   */
  AiControlPrefer *aipre;
  /*
   * 灯开关控制
   */
  protobuf_c_boolean has_lightsw;
  int32_t lightsw;
  /*
   * 谐振补偿
   */
  protobuf_c_boolean has_chatteringopt;
  int32_t chatteringopt;
  /*
   * 自动调平
   */
  protobuf_c_boolean has_autoleveling;
  int32_t autoleveling;
  /*
   * 打印前检测
   */
  protobuf_c_boolean has_withselftest;
  int32_t withselftest;
  /*
   * 打印前检测开关
   */
  protobuf_c_boolean has_enableselftest;
  int32_t enableselftest;
  /*
   * 进料
   */
  LoadQuitMaterial *loadmaterial;
  /*
   * 退料
   */
  LoadQuitMaterial *quitmaterial;
  /*
   * 打印速度模式
   */
  protobuf_c_boolean has_speedmode;
  int32_t speedmode;
  /*
   * 清除错误码
   */
  protobuf_c_boolean has_clearfaultcode;
  int32_t clearfaultcode;
  /*
   * 设置对象排除
   */
  MutableTypeData *excludeobject;
};
#define APP_CONTROL_PRINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&app_control_print__descriptor) \
    , 0,0, 0,{0,NULL}, 0,0, 0,0, NULL, NULL, NULL, 0,0, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0, 0,0, NULL, 0,0, 0,0, 0,0, 0,0, 0,0, NULL, NULL, 0,0, 0,0, NULL }


/*
 * 获取gcode文件列表
 */
struct  _GetGcodeFIleList
{
  ProtobufCMessage base;
  /*
   * 指定查找路径
   */
  protobuf_c_boolean has_path;
  ProtobufCBinaryData path;
  /*
   * 文件排序方式
   */
  protobuf_c_boolean has_sort;
  uint32_t sort;
  /*
   * 列表类型：0 本地 1 U盘
   */
  protobuf_c_boolean has_type;
  uint32_t type;
};
#define GET_GCODE_FILE_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&get_gcode_file_list__descriptor) \
    , 0,{0,NULL}, 0,0, 0,0 }


/*
 * 本地gcode文件信息
 */
struct  _LocalGcodeInfo
{
  ProtobufCMessage base;
  /*
   * 响应结果
   */
  protobuf_c_boolean has_result;
  uint32_t result;
  /*
   * 文件总数
   */
  protobuf_c_boolean has_sum;
  uint32_t sum;
  /*
   * 信息缓存路径
   */
  protobuf_c_boolean has_cachepath;
  ProtobufCBinaryData cachepath;
  /*
   * 获取指定范围文件开始ID
   */
  protobuf_c_boolean has_optstart;
  uint32_t optstart;
  /*
   * 获取指定范围文件结束ID
   */
  protobuf_c_boolean has_optend;
  uint32_t optend;
  /*
   * 选中文件ID
   */
  protobuf_c_boolean has_optfileid;
  uint32_t optfileid;
  /*
   * 注水图路径
   */
  protobuf_c_boolean has_photopath;
  ProtobufCBinaryData photopath;
  /*
   * 起始像素点
   */
  protobuf_c_boolean has_startpixel;
  uint32_t startpixel;
  /*
   * 结束像素点
   */
  protobuf_c_boolean has_endpixel;
  uint32_t endpixel;
  /*
   * 模型高度
   */
  protobuf_c_boolean has_modelheight;
  uint32_t modelheight;
  /*
   * 模型层高
   */
  protobuf_c_boolean has_layerheight;
  uint32_t layerheight;
};
#define LOCAL_GCODE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&local_gcode_info__descriptor) \
    , 0,0, 0,0, 0,{0,NULL}, 0,0, 0,0, 0,0, 0,{0,NULL}, 0,0, 0,0, 0,0, 0,0 }


/*
 * 系统设置参数
 */
struct  _SystemSetting
{
  ProtobufCMessage base;
  /*
   * 自动关机
   */
  protobuf_c_boolean has_autooff;
  int32_t autooff;
  /*
   * 开机自检
   */
  protobuf_c_boolean has_selftest;
  int32_t selftest;
  /*
   * 音频开关
   */
  protobuf_c_boolean has_soundsw;
  int32_t soundsw;
  /*
   * 屏保开关
   */
  protobuf_c_boolean has_screensaver;
  int32_t screensaver;
  /*
   * 主题选择
   */
  protobuf_c_boolean has_thememode;
  int32_t thememode;
  /*
   * 语言设置
   */
  protobuf_c_boolean has_language;
  int32_t language;
  /*
   * 屏幕亮度
   */
  protobuf_c_boolean has_screenvalue;
  int32_t screenvalue;
  /*
   * 横竖屏方向
   */
  protobuf_c_boolean has_uidirection;
  int32_t uidirection;
  /*
   * 音量大小
   */
  protobuf_c_boolean has_soundsize;
  int32_t soundsize;
  /*
   * 按键音效
   */
  protobuf_c_boolean has_soundeffect;
  int32_t soundeffect;
  /*
   * 全屏模式
   */
  protobuf_c_boolean has_fullscreen;
  int32_t fullscreen;
  /*
   * 灯光开关
   */
  protobuf_c_boolean has_lightsw;
  int32_t lightsw;
  /*
   * 灯光亮度
   */
  protobuf_c_boolean has_lightvalue;
  int32_t lightvalue;
  /*
   * 系统时区
   */
  protobuf_c_boolean has_timezone;
  ProtobufCBinaryData timezone;
  /*
   * 服务器配置 {1：正式，2：预发布，3：测试，4：联调}
   */
  protobuf_c_boolean has_serverconfig;
  int32_t serverconfig;
  /*
   * 升级提醒
   */
  protobuf_c_boolean has_upgraderemind;
  int32_t upgraderemind;
  /*
   * 服务器位置 {1：国内，2：海外}
   */
  protobuf_c_boolean has_serverlocal;
  int32_t serverlocal;
  /*
   * 同意隐私协议
   */
  protobuf_c_boolean has_agreeprivacy;
  int32_t agreeprivacy;
  /*
   * 主机名称
   */
  protobuf_c_boolean has_hostname;
  ProtobufCBinaryData hostname;
  /*
   * 用户数据采集
   */
  protobuf_c_boolean has_datacollect;
  int32_t datacollect;
};
#define SYSTEM_SETTING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system_setting__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,{0,NULL}, 0,0, 0,0, 0,0, 0,0, 0,{0,NULL}, 0,0 }


/*
 * 进退料参数
 */
struct  _LoadQuitMaterial
{
  ProtobufCMessage base;
  /*
   * 目标温度
   */
  protobuf_c_boolean has_targettemp;
  int32_t targettemp;
  /*
   * 进退料长度
   */
  protobuf_c_boolean has_length;
  int32_t length;
  /*
   * 准备长度
   */
  protobuf_c_boolean has_readylength;
  int32_t readylength;
  /*
   * 进退料速度
   */
  protobuf_c_boolean has_speed;
  int32_t speed;
};
#define LOAD_QUIT_MATERIAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&load_quit_material__descriptor) \
    , 0,0, 0,0, 0,0, 0,0 }


/*
 * 显示控制打印机
 */
struct  _DisControlPrint
{
  ProtobufCMessage base;
  /*
   * 控制执行结果
   */
  protobuf_c_boolean has_result;
  int32_t result;
  /*
   * 设置喷嘴目标温度
   */
  Extruder *nozzletemp;
  /*
   * 设置热床目标温度
   */
  HeaterBed *bedtemp;
  /*
   * 设置打印倍速
   */
  protobuf_c_boolean has_speedmultiple;
  ProtobufCBinaryData speedmultiple;
  /*
   * 设置轴补偿
   */
  protobuf_c_boolean has_axisrecoup;
  ProtobufCBinaryData axisrecoup;
  /*
   * 打印gcode文件，文件名
   */
  MutableTypeData *print;
  /*
   * 打印控制（暂停、恢复、停止）
   */
  protobuf_c_boolean has_printctr;
  int32_t printctr;
  /*
   * 控制回原点
   */
  protobuf_c_boolean has_returnhome;
  ProtobufCBinaryData returnhome;
  /*
   * 轴移动（X\Y\Z\E）
   */
  protobuf_c_boolean has_axismove;
  ProtobufCBinaryData axismove;
  /*
   * 电机锁定、解锁
   */
  protobuf_c_boolean has_motorlock;
  int32_t motorlock;
  /*
   * 风扇控制
   */
  MultiFan *fancontrol;
  /*
   * 断料检测
   */
  protobuf_c_boolean has_materialdelect;
  ProtobufCBinaryData materialdelect;
  /*
   * 断电续打
   */
  protobuf_c_boolean has_powerlosssw;
  ProtobufCBinaryData powerlosssw;
  /*
   * 设置传动比
   */
  protobuf_c_boolean has_stepvalue;
  ProtobufCBinaryData stepvalue;
  /*
   * 设置最大加速度
   */
  protobuf_c_boolean has_acceleration;
  ProtobufCBinaryData acceleration;
  /*
   * 设置最大加速到减速的加速度限制
   */
  protobuf_c_boolean has_maxjerk;
  ProtobufCBinaryData maxjerk;
  /*
   * 设置最大速度
   */
  protobuf_c_boolean has_maxspeed;
  ProtobufCBinaryData maxspeed;
  /*
   * 设置喷嘴温度PID
   */
  protobuf_c_boolean has_hotendpid;
  ProtobufCBinaryData hotendpid;
  /*
   * 设置热床温度PID
   */
  protobuf_c_boolean has_bedpid;
  ProtobufCBinaryData bedpid;
  /*
   * 设置轴偏移
   */
  protobuf_c_boolean has_axisoffset;
  ProtobufCBinaryData axisoffset;
  /*
   * 手动调平
   */
  protobuf_c_boolean has_manuallevel;
  ProtobufCBinaryData manuallevel;
  /*
   * 自动调平
   */
  protobuf_c_boolean has_autolevel;
  int32_t autolevel;
  /*
   * 自动调平点数设置
   */
  protobuf_c_boolean has_autolevelpoints;
  ProtobufCBinaryData autolevelpoints;
  /*
   * 设置CR touch
   */
  protobuf_c_boolean has_setcrtouch;
  ProtobufCBinaryData setcrtouch;
  /*
   * 设置保存参数到（EEPROM）
   */
  protobuf_c_boolean has_savepara;
  int32_t savepara;
  /*
   * 更换耗材
   */
  protobuf_c_boolean has_insertfilament;
  int32_t insertfilament;
  /*
   * 设置流量倍速
   */
  protobuf_c_boolean has_flowmultiple;
  ProtobufCBinaryData flowmultiple;
  /*
   * 执行gcode宏定义
   */
  protobuf_c_boolean has_gcodemacro;
  ProtobufCBinaryData gcodemacro;
  /*
   * 终端控制
   */
  protobuf_c_boolean has_consolectl;
  ProtobufCBinaryData consolectl;
  /*
   * 重启klipper
   */
  protobuf_c_boolean has_restartklipper;
  ProtobufCBinaryData restartklipper;
  /*
   * 重启klipper下位机
   */
  protobuf_c_boolean has_firmwarerestart;
  ProtobufCBinaryData firmwarerestart;
  /*
   * 共振补偿测试
   */
  protobuf_c_boolean has_resonancetest;
  ProtobufCBinaryData resonancetest;
  /*
   * 停止所有加热
   */
  protobuf_c_boolean has_stopallheating;
  ProtobufCBinaryData stopallheating;
  /*
   * 设置最大拐角速度
   */
  protobuf_c_boolean has_maxcorner;
  ProtobufCBinaryData maxcorner;
  /*
   * 设置压力推进
   */
  protobuf_c_boolean has_pressureadvance;
  ProtobufCBinaryData pressureadvance;
  /*
   * 设置平滑时间
   */
  protobuf_c_boolean has_smoothtime;
  ProtobufCBinaryData smoothtime;
  /*
   * 设置对象排除
   */
  MutableTypeData *excludeobject;
  /*
   * 设置热床调平数据
   */
  MutableTypeData *bedmeshinfo;
  /*
   * 恢复出厂设置
   */
  protobuf_c_boolean has_systemreset;
  int32_t systemreset;
  /*
   * 自动关机
   */
  SystemSetting *syssetting;
  /*
   * 开始升级
   */
  UpgradeInfoList *startupgrade;
  /*
   * 取消升级
   */
  UpgradeInfoList *cancelupgrade;
  /*
   * 清除错误码
   */
  protobuf_c_boolean has_clearfaultcode;
  int32_t clearfaultcode;
  /*
   * 设置材料偏好
   */
  MaterialPrefer *materialpre;
  /*
   * 开始预热
   */
  protobuf_c_boolean has_startwarmup;
  int32_t startwarmup;
  /*
   * 设置自动温度PID偏好
   */
  TempAutoPidPrefer *temppidpre;
  /*
   * 开始自动PID
   */
  protobuf_c_boolean has_startautopid;
  int32_t startautopid;
  /*
   * 设置延时摄影偏好
   */
  DelayImagePrefer *delayimagepre;
  /*
   * 设置断电续打偏好
   */
  PowerLossPrefer *powerlosspre;
  /*
   * 设置AI控制偏好
   */
  AiControlPrefer *aipre;
  /*
   * 连接wifi
   */
  NetworksInfo *connectwifi;
  /*
   * 连接已保存wifi
   */
  NetworksInfo *connectsavewifi;
  /*
   * 断开wifi
   */
  NetworksInfo *disconnectwifi;
  /*
   * 删除已保存wifi
   */
  NetworksInfo *removewifi;
  /*
   * 静音模式
   */
  protobuf_c_boolean has_quietmode;
  int32_t quietmode;
  /*
   * 静音模式
   */
  LoadQuitMaterial *loadmaterial;
  /*
   * 静音模式
   */
  LoadQuitMaterial *quitmaterial;
  /*
   * 上传本地视频
   */
  protobuf_c_boolean has_uploadlocalvideo;
  ProtobufCBinaryData uploadlocalvideo;
  /*
   * 上传本地日志
   */
  protobuf_c_boolean has_uploadlocallog;
  ProtobufCBinaryData uploadlocallog;
  /*
   * 获取用户创想云信息
   */
  protobuf_c_boolean has_updateusercxyinfo;
  int32_t updateusercxyinfo;
  /*
   * 激光校准
   */
  protobuf_c_boolean has_lasercalibration;
  int32_t lasercalibration;
};
#define DIS_CONTROL_PRINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dis_control_print__descriptor) \
    , 0,0, NULL, NULL, 0,{0,NULL}, 0,{0,NULL}, NULL, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,0, NULL, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, NULL, NULL, 0,0, NULL, NULL, NULL, 0,0, NULL, 0,0, NULL, 0,0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0,0, NULL, NULL, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0 }


/*
 * 自动PID结果
 */
struct  _AutoPidResult
{
  ProtobufCMessage base;
  /*
   * 喷嘴
   */
  PidInfo *hotend;
  /*
   * 热床
   */
  PidInfo *hotbed;
};
#define AUTO_PID_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&auto_pid_result__descriptor) \
    , NULL, NULL }


/*
 * 打印机保存参数
 */
struct  _ReportAutoLevelRes
{
  ProtobufCMessage base;
  /*
   * 调平点号
   */
  protobuf_c_boolean has_num;
  int32_t num;
  /*
   * 当前点的X坐标
   */
  protobuf_c_boolean has_pointx;
  int32_t pointx;
  /*
   * 当前点的Y坐标
   */
  protobuf_c_boolean has_pointy;
  int32_t pointy;
  /*
   * 当前点的偏移值
   */
  protobuf_c_boolean has_value;
  int32_t value;
};
#define REPORT_AUTO_LEVEL_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&report_auto_level_res__descriptor) \
    , 0,0, 0,0, 0,0, 0,0 }


/*
 * 打印机升级信息
 */
struct  _UpgradeInfo
{
  ProtobufCMessage base;
  /*
   * 是否强制升级
   */
  protobuf_c_boolean has_force;
  int32_t force;
  /*
   * 升级版本
   */
  protobuf_c_boolean has_version;
  ProtobufCBinaryData version;
  /*
   * 镜像名称
   */
  protobuf_c_boolean has_name;
  ProtobufCBinaryData name;
  /*
   * 镜像大小
   */
  protobuf_c_boolean has_size;
  int32_t size;
  /*
   * 升级说明
   */
  protobuf_c_boolean has_manual;
  ProtobufCBinaryData manual;
  /*
   * 镜像下载地址
   */
  protobuf_c_boolean has_url;
  ProtobufCBinaryData url;
  /*
   * 下载进度
   */
  protobuf_c_boolean has_progress;
  int32_t progress;
  /*
   * 升级镜像路径（U盘升级使用）
   */
  protobuf_c_boolean has_imagepath;
  ProtobufCBinaryData imagepath;
  /*
   * 升级状态
   */
  protobuf_c_boolean has_state;
  int32_t state;
};
#define UPGRADE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&upgrade_info__descriptor) \
    , 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,{0,NULL}, 0,0 }


/*
 * 打印机升级信息列表
 */
struct  _UpgradeInfoList
{
  ProtobufCMessage base;
  /*
   * Linux OTA升级
   */
  UpgradeInfo *linuxota;
  /*
   * Linux 本地升级
   */
  UpgradeInfo *linuxlocal;
  /*
   * mcu1 OTA升级
   */
  UpgradeInfo *mcu1ota;
  /*
   * mcu1 本地升级
   */
  UpgradeInfo *mcu1local;
  /*
   * mcu2 OTA升级
   */
  UpgradeInfo *mcu2ota;
  /*
   * mcu2 本地升级
   */
  UpgradeInfo *mcu2local;
  /*
   * mcu3 OTA升级
   */
  UpgradeInfo *mcu3ota;
  /*
   * mcu3 本地升级
   */
  UpgradeInfo *mcu3local;
};
#define UPGRADE_INFO_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&upgrade_info_list__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


/*
 * 打印历史记录
 */
struct  _HistoryRecord
{
  ProtobufCMessage base;
  /*
   * 打印任务ID
   */
  int32_t id;
  /*
   * 打印文件名称
   */
  ProtobufCBinaryData filename;
  /*
   * 文件大小
   */
  int32_t size;
  /*
   * 创建时间
   */
  int32_t ctime;
  /*
   * 打印开始时间
   */
  int32_t starttime;
  /*
   * 启动打印方式（UI、APP、...）
   */
  int32_t startway;
  /*
   * 累计使用时间
   */
  int32_t usagetime;
  /*
   * 累计使用耗材
   */
  double usagematerial;
  /*
   * 打印是否完成
   */
  int32_t printfinish;
  /*
   * 缩略图路径
   */
  ProtobufCBinaryData thumbnail;
  /*
   * 打印文件MD5码
   */
  ProtobufCBinaryData filemd5;
};
#define HISTORY_RECORD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&history_record__descriptor) \
    , 0, {0,NULL}, 0, 0, 0, 0, 0, 0, 0, {0,NULL}, {0,NULL} }


/*
 * 打印历史记录列表
 */
struct  _HistoryRecordList
{
  ProtobufCMessage base;
  /*
   * 打印历史记录
   */
  size_t n_list;
  HistoryRecord **list;
};
#define HISTORY_RECORD_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&history_record_list__descriptor) \
    , 0,NULL }


/*
 * 延时摄影信息
 */
struct  _DelayImageInfo
{
  ProtobufCMessage base;
  /*
   * gcode名称
   */
  ProtobufCBinaryData name;
  /*
   * ID
   */
  int32_t id;
  /*
   * 视频路径
   */
  ProtobufCBinaryData video;
  /*
   * 大小
   */
  int32_t size;
  /*
   * 时长
   */
  int32_t duration;
  /*
   * 封面
   */
  ProtobufCBinaryData cover;
  /*
   * 开始时间
   */
  int32_t starttime;
  /*
   * 打印时间
   */
  int32_t printtime;
  /*
   * 喷嘴位置
   */
  int32_t location;
  /*
   * 间隔层数
   */
  int32_t interval;
  /*
   * 渲染帧数
   */
  int32_t render;
};
#define DELAY_IMAGE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&delay_image_info__descriptor) \
    , {0,NULL}, 0, {0,NULL}, 0, 0, {0,NULL}, 0, 0, 0, 0, 0 }


/*
 * 延时摄影信息列表
 */
struct  _DelayImageInfoList
{
  ProtobufCMessage base;
  /*
   * 延时摄影信息
   */
  size_t n_list;
  DelayImageInfo **list;
};
#define DELAY_IMAGE_INFO_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&delay_image_info_list__descriptor) \
    , 0,NULL }


/*
 * 定义可变类型数据
 */
struct  _MutableTypeData
{
  ProtobufCMessage base;
  protobuf_c_boolean has_bool_v;
  protobuf_c_boolean bool_v;
  protobuf_c_boolean has_int_v;
  int32_t int_v;
  protobuf_c_boolean has_double_v;
  double double_v;
  protobuf_c_boolean has_bytes_v;
  ProtobufCBinaryData bytes_v;
};
#define MUTABLE_TYPE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mutable_type_data__descriptor) \
    , 0,0, 0,0, 0,0, 0,{0,NULL} }


/*
 * 错误状态消息体
 */
struct  _UpdataErrorInfo
{
  ProtobufCMessage base;
  /*
   * 错误码
   */
  int32_t code;
  /*
   * 交互提示 
   */
  int32_t error;
  /*
   * 错误消息
   */
  ProtobufCBinaryData msg;
  /*
   * 错误参数
   */
  ProtobufCBinaryData values;
};
#define UPDATA_ERROR_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&updata_error_info__descriptor) \
    , 0, 0, {0,NULL}, {0,NULL} }


/*
 * 多热床控制
 */
struct  _MultipleBedTemp
{
  ProtobufCMessage base;
  protobuf_c_boolean has_bedtemp0;
  int32_t bedtemp0;
  protobuf_c_boolean has_bedtemp1;
  int32_t bedtemp1;
  protobuf_c_boolean has_bedtemp2;
  int32_t bedtemp2;
};
#define MULTIPLE_BED_TEMP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&multiple_bed_temp__descriptor) \
    , 0,0, 0,0, 0,0 }


/*
 * WEB控制打印机
 */
struct  _WebControlPrint
{
  ProtobufCMessage base;
  /*
   * 控制执行结果
   */
  protobuf_c_boolean has_result;
  int32_t result;
  /*
   * 开启云打印
   */
  protobuf_c_boolean has_print;
  ProtobufCBinaryData print;
  /*
   * 打印控制（暂停、恢复）
   */
  protobuf_c_boolean has_pause;
  int32_t pause;
  /*
   * 打印控制（停止）
   */
  protobuf_c_boolean has_stop;
  int32_t stop;
  /*
   * 设置喷嘴目标温度
   */
  Extruder *nozzletemp;
  /*
   * 设置热床目标温度
   */
  HeaterBed *bedtemp;
  /*
   * 风扇控制
   */
  MultiFan *fan;
  /*
   * 断电续打控制
   */
  protobuf_c_boolean has_offcontinue;
  int32_t offcontinue;
  /*
   * 控制回原点
   */
  protobuf_c_boolean has_autohome;
  ProtobufCBinaryData autohome;
  /*
   * 本地打印 
   */
  protobuf_c_boolean has_opgcodefile;
  ProtobufCBinaryData opgcodefile;
  /*
   * 轴移动（X\Y\Z\E）
   */
  protobuf_c_boolean has_setposition;
  ProtobufCBinaryData setposition;
  /*
   * 设置打印倍速
   */
  protobuf_c_boolean has_setfeedratepct;
  ProtobufCBinaryData setfeedratepct;
  /*
   * 设置流量倍速
   */
  protobuf_c_boolean has_setflowratepct;
  ProtobufCBinaryData setflowratepct;
  /*
   * 执行gcode宏定义
   */
  protobuf_c_boolean has_gcodecmd;
  ProtobufCBinaryData gcodecmd;
  /*
   * 设置轴补偿
   */
  protobuf_c_boolean has_axisrecoup;
  ProtobufCBinaryData axisrecoup;
  /*
   * 电机关闭控制
   */
  protobuf_c_boolean has_motorlock;
  int32_t motorlock;
  /*
   * 一键冷却
   */
  protobuf_c_boolean has_heatersoff;
  int32_t heatersoff;
  /*
   * 速度限制
   */
  protobuf_c_boolean has_velocitylimits;
  ProtobufCBinaryData velocitylimits;
  /*
   * 加速度限制
   */
  protobuf_c_boolean has_accelerationlimits;
  ProtobufCBinaryData accelerationlimits;
  /*
   * 删除文件
   */
  protobuf_c_boolean has_delete_;
  ProtobufCBinaryData delete_;
  /*
   * 重命名文件
   */
  protobuf_c_boolean has_rename;
  ProtobufCBinaryData rename;
  /*
   * 延时摄影开关
   */
  protobuf_c_boolean has_videoelapse;
  int32_t videoelapse;
  /*
   * 延时摄影移开喷嘴
   */
  protobuf_c_boolean has_nozzlemovesnapshot;
  int32_t nozzlemovesnapshot;
  /*
   * 延时摄影帧数
   */
  protobuf_c_boolean has_videoelapseframe;
  int32_t videoelapseframe;
  /*
   * 延时摄影拍摄间隔
   */
  protobuf_c_boolean has_videoelapseinterval;
  int32_t videoelapseinterval;
  /*
   * 断料检测
   */
  protobuf_c_boolean has_materialdetect;
  ProtobufCBinaryData materialdetect;
  /*
   * 断电续打
   */
  protobuf_c_boolean has_powerlosssw;
  int32_t powerlosssw;
  /*
   * 拐角速度限制
   */
  protobuf_c_boolean has_cornervelocitylimits;
  ProtobufCBinaryData cornervelocitylimits;
  /*
   * 加速到减速的加速度限制
   */
  protobuf_c_boolean has_acceltodecellimits;
  ProtobufCBinaryData acceltodecellimits;
  /*
   * 压力推进设置
   */
  protobuf_c_boolean has_pressureadvance;
  ProtobufCBinaryData pressureadvance;
  /*
   * 平滑时间设置
   */
  protobuf_c_boolean has_smoothtime;
  ProtobufCBinaryData smoothtime;
  /*
   * 设置热床温度PID偏好
   */
  protobuf_c_boolean has_bedtempautopid;
  int32_t bedtempautopid;
  /*
   * 设置喷嘴温度PID偏好
   */
  protobuf_c_boolean has_nozzletempautopid;
  int32_t nozzletempautopid;
  /*
   * 开始自动PID
   */
  protobuf_c_boolean has_startautopid;
  int32_t startautopid;
  /*
   * 谐振补偿测试
   */
  protobuf_c_boolean has_resonancetest;
  ProtobufCBinaryData resonancetest;
  /*
   * 手动调平
   */
  protobuf_c_boolean has_manuallevel;
  ProtobufCBinaryData manuallevel;
  /*
   * 自动调平
   */
  protobuf_c_boolean has_autolevel;
  int32_t autolevel;
  /*
   * 重启klipper
   */
  protobuf_c_boolean has_restartklipper;
  int32_t restartklipper;
  /*
   * 重启下位机
   */
  protobuf_c_boolean has_restartfirmware;
  int32_t restartfirmware;
  /*
   * 重启系统
   */
  protobuf_c_boolean has_restartsystem;
  int32_t restartsystem;
  /*
   * 恢复出厂设置
   */
  protobuf_c_boolean has_resetsystem;
  int32_t resetsystem;
  /*
   * 升级
   */
  UpgradeInfoList *upgrade;
  /*
   * 灯开关控制
   */
  protobuf_c_boolean has_lightsw;
  int32_t lightsw;
  /*
   * 设置保存参数到（EEPROM）
   */
  protobuf_c_boolean has_savepara;
  int32_t savepara;
  /*
   * AI控制参数
   */
  AiControlPrefer *aipre;
  /*
   * 清除错误码
   */
  protobuf_c_boolean has_clearfaultcode;
  int32_t clearfaultcode;
  /*
   * 打印前检测开关
   */
  protobuf_c_boolean has_enableselftest;
  int32_t enableselftest;
  /*
   * 设置对象排除
   */
  MutableTypeData *excludeobject;
};
#define WEB_CONTROL_PRINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&web_control_print__descriptor) \
    , 0,0, 0,{0,NULL}, 0,0, 0,0, NULL, NULL, NULL, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0, 0,0, 0,0, 0,{0,NULL}, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0, 0,0, 0,0, 0,0, NULL, 0,0, 0,0, NULL, 0,0, 0,0, NULL }


struct  _FileControl
{
  ProtobufCMessage base;
  /*
   * 1、添加printid。 2、重命名。3、刪除。4、修改上传状态。
   */
  protobuf_c_boolean has_cmd;
  int32_t cmd;
  /*
   * 文件
   */
  protobuf_c_boolean has_file;
  ProtobufCBinaryData file;
  /*
   *打印id
   */
  protobuf_c_boolean has_printid;
  ProtobufCBinaryData printid;
  /*
   * other param
   */
  protobuf_c_boolean has_param1;
  ProtobufCBinaryData param1;
  protobuf_c_boolean has_param2;
  ProtobufCBinaryData param2;
};
#define FILE_CONTROL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file_control__descriptor) \
    , 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL} }


/*
 * 下载gcode状态信息
 */
struct  _DownloadGcode
{
  ProtobufCMessage base;
  /*
   * 下载状态
   */
  protobuf_c_boolean has_state;
  int32_t state;
  /*
   * 下载进度
   */
  protobuf_c_boolean has_progress;
  int32_t progress;
};
#define DOWNLOAD_GCODE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&download_gcode__descriptor) \
    , 0,0, 0,0 }


/*
 * 升级重启状态同步
 */
struct  _UpgradeRebootSync
{
  ProtobufCMessage base;
  /*
   * 升级状态
   */
  int32_t state;
  /*
   * 旧版本号
   */
  ProtobufCBinaryData oldversion;
};
#define UPGRADE_REBOOT_SYNC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&upgrade_reboot_sync__descriptor) \
    , 0, {0,NULL} }


/*
 * 导出日志状态
 */
struct  _ExportLogState
{
  ProtobufCMessage base;
  /*
   * 导出状态
   */
  int32_t state;
  /*
   * 导出进度
   */
  int32_t progress;
};
#define EXPORT_LOG_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&export_log_state__descriptor) \
    , 0, 0 }


/* ServerTest methods */
void   server_test__init
                     (ServerTest         *message);
size_t server_test__get_packed_size
                     (const ServerTest   *message);
size_t server_test__pack
                     (const ServerTest   *message,
                      uint8_t             *out);
size_t server_test__pack_to_buffer
                     (const ServerTest   *message,
                      ProtobufCBuffer     *buffer);
ServerTest *
       server_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_test__free_unpacked
                     (ServerTest *message,
                      ProtobufCAllocator *allocator);
/* GeneralRes methods */
void   general_res__init
                     (GeneralRes         *message);
size_t general_res__get_packed_size
                     (const GeneralRes   *message);
size_t general_res__pack
                     (const GeneralRes   *message,
                      uint8_t             *out);
size_t general_res__pack_to_buffer
                     (const GeneralRes   *message,
                      ProtobufCBuffer     *buffer);
GeneralRes *
       general_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   general_res__free_unpacked
                     (GeneralRes *message,
                      ProtobufCAllocator *allocator);
/* SendString methods */
void   send_string__init
                     (SendString         *message);
size_t send_string__get_packed_size
                     (const SendString   *message);
size_t send_string__pack
                     (const SendString   *message,
                      uint8_t             *out);
size_t send_string__pack_to_buffer
                     (const SendString   *message,
                      ProtobufCBuffer     *buffer);
SendString *
       send_string__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   send_string__free_unpacked
                     (SendString *message,
                      ProtobufCAllocator *allocator);
/* MaterialPrefer methods */
void   material_prefer__init
                     (MaterialPrefer         *message);
size_t material_prefer__get_packed_size
                     (const MaterialPrefer   *message);
size_t material_prefer__pack
                     (const MaterialPrefer   *message,
                      uint8_t             *out);
size_t material_prefer__pack_to_buffer
                     (const MaterialPrefer   *message,
                      ProtobufCBuffer     *buffer);
MaterialPrefer *
       material_prefer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   material_prefer__free_unpacked
                     (MaterialPrefer *message,
                      ProtobufCAllocator *allocator);
/* MaterialPreferList methods */
void   material_prefer_list__init
                     (MaterialPreferList         *message);
size_t material_prefer_list__get_packed_size
                     (const MaterialPreferList   *message);
size_t material_prefer_list__pack
                     (const MaterialPreferList   *message,
                      uint8_t             *out);
size_t material_prefer_list__pack_to_buffer
                     (const MaterialPreferList   *message,
                      ProtobufCBuffer     *buffer);
MaterialPreferList *
       material_prefer_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   material_prefer_list__free_unpacked
                     (MaterialPreferList *message,
                      ProtobufCAllocator *allocator);
/* TempAutoPidPrefer methods */
void   temp_auto_pid_prefer__init
                     (TempAutoPidPrefer         *message);
size_t temp_auto_pid_prefer__get_packed_size
                     (const TempAutoPidPrefer   *message);
size_t temp_auto_pid_prefer__pack
                     (const TempAutoPidPrefer   *message,
                      uint8_t             *out);
size_t temp_auto_pid_prefer__pack_to_buffer
                     (const TempAutoPidPrefer   *message,
                      ProtobufCBuffer     *buffer);
TempAutoPidPrefer *
       temp_auto_pid_prefer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   temp_auto_pid_prefer__free_unpacked
                     (TempAutoPidPrefer *message,
                      ProtobufCAllocator *allocator);
/* TempAutoPidPreferList methods */
void   temp_auto_pid_prefer_list__init
                     (TempAutoPidPreferList         *message);
size_t temp_auto_pid_prefer_list__get_packed_size
                     (const TempAutoPidPreferList   *message);
size_t temp_auto_pid_prefer_list__pack
                     (const TempAutoPidPreferList   *message,
                      uint8_t             *out);
size_t temp_auto_pid_prefer_list__pack_to_buffer
                     (const TempAutoPidPreferList   *message,
                      ProtobufCBuffer     *buffer);
TempAutoPidPreferList *
       temp_auto_pid_prefer_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   temp_auto_pid_prefer_list__free_unpacked
                     (TempAutoPidPreferList *message,
                      ProtobufCAllocator *allocator);
/* DelayImagePrefer methods */
void   delay_image_prefer__init
                     (DelayImagePrefer         *message);
size_t delay_image_prefer__get_packed_size
                     (const DelayImagePrefer   *message);
size_t delay_image_prefer__pack
                     (const DelayImagePrefer   *message,
                      uint8_t             *out);
size_t delay_image_prefer__pack_to_buffer
                     (const DelayImagePrefer   *message,
                      ProtobufCBuffer     *buffer);
DelayImagePrefer *
       delay_image_prefer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   delay_image_prefer__free_unpacked
                     (DelayImagePrefer *message,
                      ProtobufCAllocator *allocator);
/* PowerLossPrefer methods */
void   power_loss_prefer__init
                     (PowerLossPrefer         *message);
size_t power_loss_prefer__get_packed_size
                     (const PowerLossPrefer   *message);
size_t power_loss_prefer__pack
                     (const PowerLossPrefer   *message,
                      uint8_t             *out);
size_t power_loss_prefer__pack_to_buffer
                     (const PowerLossPrefer   *message,
                      ProtobufCBuffer     *buffer);
PowerLossPrefer *
       power_loss_prefer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   power_loss_prefer__free_unpacked
                     (PowerLossPrefer *message,
                      ProtobufCAllocator *allocator);
/* AiControlPrefer methods */
void   ai_control_prefer__init
                     (AiControlPrefer         *message);
size_t ai_control_prefer__get_packed_size
                     (const AiControlPrefer   *message);
size_t ai_control_prefer__pack
                     (const AiControlPrefer   *message,
                      uint8_t             *out);
size_t ai_control_prefer__pack_to_buffer
                     (const AiControlPrefer   *message,
                      ProtobufCBuffer     *buffer);
AiControlPrefer *
       ai_control_prefer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ai_control_prefer__free_unpacked
                     (AiControlPrefer *message,
                      ProtobufCAllocator *allocator);
/* WifiInfo methods */
void   wifi_info__init
                     (WifiInfo         *message);
size_t wifi_info__get_packed_size
                     (const WifiInfo   *message);
size_t wifi_info__pack
                     (const WifiInfo   *message,
                      uint8_t             *out);
size_t wifi_info__pack_to_buffer
                     (const WifiInfo   *message,
                      ProtobufCBuffer     *buffer);
WifiInfo *
       wifi_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wifi_info__free_unpacked
                     (WifiInfo *message,
                      ProtobufCAllocator *allocator);
/* NetworksInfo methods */
void   networks_info__init
                     (NetworksInfo         *message);
size_t networks_info__get_packed_size
                     (const NetworksInfo   *message);
size_t networks_info__pack
                     (const NetworksInfo   *message,
                      uint8_t             *out);
size_t networks_info__pack_to_buffer
                     (const NetworksInfo   *message,
                      ProtobufCBuffer     *buffer);
NetworksInfo *
       networks_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   networks_info__free_unpacked
                     (NetworksInfo *message,
                      ProtobufCAllocator *allocator);
/* SystemConfigProto methods */
void   system_config_proto__init
                     (SystemConfigProto         *message);
size_t system_config_proto__get_packed_size
                     (const SystemConfigProto   *message);
size_t system_config_proto__pack
                     (const SystemConfigProto   *message,
                      uint8_t             *out);
size_t system_config_proto__pack_to_buffer
                     (const SystemConfigProto   *message,
                      ProtobufCBuffer     *buffer);
SystemConfigProto *
       system_config_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system_config_proto__free_unpacked
                     (SystemConfigProto *message,
                      ProtobufCAllocator *allocator);
/* AxisPositionInfo methods */
void   axis_position_info__init
                     (AxisPositionInfo         *message);
size_t axis_position_info__get_packed_size
                     (const AxisPositionInfo   *message);
size_t axis_position_info__pack
                     (const AxisPositionInfo   *message,
                      uint8_t             *out);
size_t axis_position_info__pack_to_buffer
                     (const AxisPositionInfo   *message,
                      ProtobufCBuffer     *buffer);
AxisPositionInfo *
       axis_position_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   axis_position_info__free_unpacked
                     (AxisPositionInfo *message,
                      ProtobufCAllocator *allocator);
/* PidInfo methods */
void   pid_info__init
                     (PidInfo         *message);
size_t pid_info__get_packed_size
                     (const PidInfo   *message);
size_t pid_info__pack
                     (const PidInfo   *message,
                      uint8_t             *out);
size_t pid_info__pack_to_buffer
                     (const PidInfo   *message,
                      ProtobufCBuffer     *buffer);
PidInfo *
       pid_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pid_info__free_unpacked
                     (PidInfo *message,
                      ProtobufCAllocator *allocator);
/* Extruder methods */
void   extruder__init
                     (Extruder         *message);
size_t extruder__get_packed_size
                     (const Extruder   *message);
size_t extruder__pack
                     (const Extruder   *message,
                      uint8_t             *out);
size_t extruder__pack_to_buffer
                     (const Extruder   *message,
                      ProtobufCBuffer     *buffer);
Extruder *
       extruder__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   extruder__free_unpacked
                     (Extruder *message,
                      ProtobufCAllocator *allocator);
/* HeaterBed methods */
void   heater_bed__init
                     (HeaterBed         *message);
size_t heater_bed__get_packed_size
                     (const HeaterBed   *message);
size_t heater_bed__pack
                     (const HeaterBed   *message,
                      uint8_t             *out);
size_t heater_bed__pack_to_buffer
                     (const HeaterBed   *message,
                      ProtobufCBuffer     *buffer);
HeaterBed *
       heater_bed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   heater_bed__free_unpacked
                     (HeaterBed *message,
                      ProtobufCAllocator *allocator);
/* MultiFan methods */
void   multi_fan__init
                     (MultiFan         *message);
size_t multi_fan__get_packed_size
                     (const MultiFan   *message);
size_t multi_fan__pack
                     (const MultiFan   *message,
                      uint8_t             *out);
size_t multi_fan__pack_to_buffer
                     (const MultiFan   *message,
                      ProtobufCBuffer     *buffer);
MultiFan *
       multi_fan__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   multi_fan__free_unpacked
                     (MultiFan *message,
                      ProtobufCAllocator *allocator);
/* MultiGsensor methods */
void   multi_gsensor__init
                     (MultiGsensor         *message);
size_t multi_gsensor__get_packed_size
                     (const MultiGsensor   *message);
size_t multi_gsensor__pack
                     (const MultiGsensor   *message,
                      uint8_t             *out);
size_t multi_gsensor__pack_to_buffer
                     (const MultiGsensor   *message,
                      ProtobufCBuffer     *buffer);
MultiGsensor *
       multi_gsensor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   multi_gsensor__free_unpacked
                     (MultiGsensor *message,
                      ProtobufCAllocator *allocator);
/* PrintWorkInfo methods */
void   print_work_info__init
                     (PrintWorkInfo         *message);
size_t print_work_info__get_packed_size
                     (const PrintWorkInfo   *message);
size_t print_work_info__pack
                     (const PrintWorkInfo   *message,
                      uint8_t             *out);
size_t print_work_info__pack_to_buffer
                     (const PrintWorkInfo   *message,
                      ProtobufCBuffer     *buffer);
PrintWorkInfo *
       print_work_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   print_work_info__free_unpacked
                     (PrintWorkInfo *message,
                      ProtobufCAllocator *allocator);
/* PrintSavePara methods */
void   print_save_para__init
                     (PrintSavePara         *message);
size_t print_save_para__get_packed_size
                     (const PrintSavePara   *message);
size_t print_save_para__pack
                     (const PrintSavePara   *message,
                      uint8_t             *out);
size_t print_save_para__pack_to_buffer
                     (const PrintSavePara   *message,
                      ProtobufCBuffer     *buffer);
PrintSavePara *
       print_save_para__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   print_save_para__free_unpacked
                     (PrintSavePara *message,
                      ProtobufCAllocator *allocator);
/* SyncPrintState methods */
void   sync_print_state__init
                     (SyncPrintState         *message);
size_t sync_print_state__get_packed_size
                     (const SyncPrintState   *message);
size_t sync_print_state__pack
                     (const SyncPrintState   *message,
                      uint8_t             *out);
size_t sync_print_state__pack_to_buffer
                     (const SyncPrintState   *message,
                      ProtobufCBuffer     *buffer);
SyncPrintState *
       sync_print_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sync_print_state__free_unpacked
                     (SyncPrintState *message,
                      ProtobufCAllocator *allocator);
/* AppControlPrint methods */
void   app_control_print__init
                     (AppControlPrint         *message);
size_t app_control_print__get_packed_size
                     (const AppControlPrint   *message);
size_t app_control_print__pack
                     (const AppControlPrint   *message,
                      uint8_t             *out);
size_t app_control_print__pack_to_buffer
                     (const AppControlPrint   *message,
                      ProtobufCBuffer     *buffer);
AppControlPrint *
       app_control_print__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   app_control_print__free_unpacked
                     (AppControlPrint *message,
                      ProtobufCAllocator *allocator);
/* GetGcodeFIleList methods */
void   get_gcode_file_list__init
                     (GetGcodeFIleList         *message);
size_t get_gcode_file_list__get_packed_size
                     (const GetGcodeFIleList   *message);
size_t get_gcode_file_list__pack
                     (const GetGcodeFIleList   *message,
                      uint8_t             *out);
size_t get_gcode_file_list__pack_to_buffer
                     (const GetGcodeFIleList   *message,
                      ProtobufCBuffer     *buffer);
GetGcodeFIleList *
       get_gcode_file_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   get_gcode_file_list__free_unpacked
                     (GetGcodeFIleList *message,
                      ProtobufCAllocator *allocator);
/* LocalGcodeInfo methods */
void   local_gcode_info__init
                     (LocalGcodeInfo         *message);
size_t local_gcode_info__get_packed_size
                     (const LocalGcodeInfo   *message);
size_t local_gcode_info__pack
                     (const LocalGcodeInfo   *message,
                      uint8_t             *out);
size_t local_gcode_info__pack_to_buffer
                     (const LocalGcodeInfo   *message,
                      ProtobufCBuffer     *buffer);
LocalGcodeInfo *
       local_gcode_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   local_gcode_info__free_unpacked
                     (LocalGcodeInfo *message,
                      ProtobufCAllocator *allocator);
/* SystemSetting methods */
void   system_setting__init
                     (SystemSetting         *message);
size_t system_setting__get_packed_size
                     (const SystemSetting   *message);
size_t system_setting__pack
                     (const SystemSetting   *message,
                      uint8_t             *out);
size_t system_setting__pack_to_buffer
                     (const SystemSetting   *message,
                      ProtobufCBuffer     *buffer);
SystemSetting *
       system_setting__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system_setting__free_unpacked
                     (SystemSetting *message,
                      ProtobufCAllocator *allocator);
/* LoadQuitMaterial methods */
void   load_quit_material__init
                     (LoadQuitMaterial         *message);
size_t load_quit_material__get_packed_size
                     (const LoadQuitMaterial   *message);
size_t load_quit_material__pack
                     (const LoadQuitMaterial   *message,
                      uint8_t             *out);
size_t load_quit_material__pack_to_buffer
                     (const LoadQuitMaterial   *message,
                      ProtobufCBuffer     *buffer);
LoadQuitMaterial *
       load_quit_material__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   load_quit_material__free_unpacked
                     (LoadQuitMaterial *message,
                      ProtobufCAllocator *allocator);
/* DisControlPrint methods */
void   dis_control_print__init
                     (DisControlPrint         *message);
size_t dis_control_print__get_packed_size
                     (const DisControlPrint   *message);
size_t dis_control_print__pack
                     (const DisControlPrint   *message,
                      uint8_t             *out);
size_t dis_control_print__pack_to_buffer
                     (const DisControlPrint   *message,
                      ProtobufCBuffer     *buffer);
DisControlPrint *
       dis_control_print__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dis_control_print__free_unpacked
                     (DisControlPrint *message,
                      ProtobufCAllocator *allocator);
/* AutoPidResult methods */
void   auto_pid_result__init
                     (AutoPidResult         *message);
size_t auto_pid_result__get_packed_size
                     (const AutoPidResult   *message);
size_t auto_pid_result__pack
                     (const AutoPidResult   *message,
                      uint8_t             *out);
size_t auto_pid_result__pack_to_buffer
                     (const AutoPidResult   *message,
                      ProtobufCBuffer     *buffer);
AutoPidResult *
       auto_pid_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   auto_pid_result__free_unpacked
                     (AutoPidResult *message,
                      ProtobufCAllocator *allocator);
/* ReportAutoLevelRes methods */
void   report_auto_level_res__init
                     (ReportAutoLevelRes         *message);
size_t report_auto_level_res__get_packed_size
                     (const ReportAutoLevelRes   *message);
size_t report_auto_level_res__pack
                     (const ReportAutoLevelRes   *message,
                      uint8_t             *out);
size_t report_auto_level_res__pack_to_buffer
                     (const ReportAutoLevelRes   *message,
                      ProtobufCBuffer     *buffer);
ReportAutoLevelRes *
       report_auto_level_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   report_auto_level_res__free_unpacked
                     (ReportAutoLevelRes *message,
                      ProtobufCAllocator *allocator);
/* UpgradeInfo methods */
void   upgrade_info__init
                     (UpgradeInfo         *message);
size_t upgrade_info__get_packed_size
                     (const UpgradeInfo   *message);
size_t upgrade_info__pack
                     (const UpgradeInfo   *message,
                      uint8_t             *out);
size_t upgrade_info__pack_to_buffer
                     (const UpgradeInfo   *message,
                      ProtobufCBuffer     *buffer);
UpgradeInfo *
       upgrade_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   upgrade_info__free_unpacked
                     (UpgradeInfo *message,
                      ProtobufCAllocator *allocator);
/* UpgradeInfoList methods */
void   upgrade_info_list__init
                     (UpgradeInfoList         *message);
size_t upgrade_info_list__get_packed_size
                     (const UpgradeInfoList   *message);
size_t upgrade_info_list__pack
                     (const UpgradeInfoList   *message,
                      uint8_t             *out);
size_t upgrade_info_list__pack_to_buffer
                     (const UpgradeInfoList   *message,
                      ProtobufCBuffer     *buffer);
UpgradeInfoList *
       upgrade_info_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   upgrade_info_list__free_unpacked
                     (UpgradeInfoList *message,
                      ProtobufCAllocator *allocator);
/* HistoryRecord methods */
void   history_record__init
                     (HistoryRecord         *message);
size_t history_record__get_packed_size
                     (const HistoryRecord   *message);
size_t history_record__pack
                     (const HistoryRecord   *message,
                      uint8_t             *out);
size_t history_record__pack_to_buffer
                     (const HistoryRecord   *message,
                      ProtobufCBuffer     *buffer);
HistoryRecord *
       history_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   history_record__free_unpacked
                     (HistoryRecord *message,
                      ProtobufCAllocator *allocator);
/* HistoryRecordList methods */
void   history_record_list__init
                     (HistoryRecordList         *message);
size_t history_record_list__get_packed_size
                     (const HistoryRecordList   *message);
size_t history_record_list__pack
                     (const HistoryRecordList   *message,
                      uint8_t             *out);
size_t history_record_list__pack_to_buffer
                     (const HistoryRecordList   *message,
                      ProtobufCBuffer     *buffer);
HistoryRecordList *
       history_record_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   history_record_list__free_unpacked
                     (HistoryRecordList *message,
                      ProtobufCAllocator *allocator);
/* DelayImageInfo methods */
void   delay_image_info__init
                     (DelayImageInfo         *message);
size_t delay_image_info__get_packed_size
                     (const DelayImageInfo   *message);
size_t delay_image_info__pack
                     (const DelayImageInfo   *message,
                      uint8_t             *out);
size_t delay_image_info__pack_to_buffer
                     (const DelayImageInfo   *message,
                      ProtobufCBuffer     *buffer);
DelayImageInfo *
       delay_image_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   delay_image_info__free_unpacked
                     (DelayImageInfo *message,
                      ProtobufCAllocator *allocator);
/* DelayImageInfoList methods */
void   delay_image_info_list__init
                     (DelayImageInfoList         *message);
size_t delay_image_info_list__get_packed_size
                     (const DelayImageInfoList   *message);
size_t delay_image_info_list__pack
                     (const DelayImageInfoList   *message,
                      uint8_t             *out);
size_t delay_image_info_list__pack_to_buffer
                     (const DelayImageInfoList   *message,
                      ProtobufCBuffer     *buffer);
DelayImageInfoList *
       delay_image_info_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   delay_image_info_list__free_unpacked
                     (DelayImageInfoList *message,
                      ProtobufCAllocator *allocator);
/* MutableTypeData methods */
void   mutable_type_data__init
                     (MutableTypeData         *message);
size_t mutable_type_data__get_packed_size
                     (const MutableTypeData   *message);
size_t mutable_type_data__pack
                     (const MutableTypeData   *message,
                      uint8_t             *out);
size_t mutable_type_data__pack_to_buffer
                     (const MutableTypeData   *message,
                      ProtobufCBuffer     *buffer);
MutableTypeData *
       mutable_type_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mutable_type_data__free_unpacked
                     (MutableTypeData *message,
                      ProtobufCAllocator *allocator);
/* UpdataErrorInfo methods */
void   updata_error_info__init
                     (UpdataErrorInfo         *message);
size_t updata_error_info__get_packed_size
                     (const UpdataErrorInfo   *message);
size_t updata_error_info__pack
                     (const UpdataErrorInfo   *message,
                      uint8_t             *out);
size_t updata_error_info__pack_to_buffer
                     (const UpdataErrorInfo   *message,
                      ProtobufCBuffer     *buffer);
UpdataErrorInfo *
       updata_error_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   updata_error_info__free_unpacked
                     (UpdataErrorInfo *message,
                      ProtobufCAllocator *allocator);
/* MultipleBedTemp methods */
void   multiple_bed_temp__init
                     (MultipleBedTemp         *message);
size_t multiple_bed_temp__get_packed_size
                     (const MultipleBedTemp   *message);
size_t multiple_bed_temp__pack
                     (const MultipleBedTemp   *message,
                      uint8_t             *out);
size_t multiple_bed_temp__pack_to_buffer
                     (const MultipleBedTemp   *message,
                      ProtobufCBuffer     *buffer);
MultipleBedTemp *
       multiple_bed_temp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   multiple_bed_temp__free_unpacked
                     (MultipleBedTemp *message,
                      ProtobufCAllocator *allocator);
/* WebControlPrint methods */
void   web_control_print__init
                     (WebControlPrint         *message);
size_t web_control_print__get_packed_size
                     (const WebControlPrint   *message);
size_t web_control_print__pack
                     (const WebControlPrint   *message,
                      uint8_t             *out);
size_t web_control_print__pack_to_buffer
                     (const WebControlPrint   *message,
                      ProtobufCBuffer     *buffer);
WebControlPrint *
       web_control_print__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   web_control_print__free_unpacked
                     (WebControlPrint *message,
                      ProtobufCAllocator *allocator);
/* FileControl methods */
void   file_control__init
                     (FileControl         *message);
size_t file_control__get_packed_size
                     (const FileControl   *message);
size_t file_control__pack
                     (const FileControl   *message,
                      uint8_t             *out);
size_t file_control__pack_to_buffer
                     (const FileControl   *message,
                      ProtobufCBuffer     *buffer);
FileControl *
       file_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file_control__free_unpacked
                     (FileControl *message,
                      ProtobufCAllocator *allocator);
/* DownloadGcode methods */
void   download_gcode__init
                     (DownloadGcode         *message);
size_t download_gcode__get_packed_size
                     (const DownloadGcode   *message);
size_t download_gcode__pack
                     (const DownloadGcode   *message,
                      uint8_t             *out);
size_t download_gcode__pack_to_buffer
                     (const DownloadGcode   *message,
                      ProtobufCBuffer     *buffer);
DownloadGcode *
       download_gcode__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   download_gcode__free_unpacked
                     (DownloadGcode *message,
                      ProtobufCAllocator *allocator);
/* UpgradeRebootSync methods */
void   upgrade_reboot_sync__init
                     (UpgradeRebootSync         *message);
size_t upgrade_reboot_sync__get_packed_size
                     (const UpgradeRebootSync   *message);
size_t upgrade_reboot_sync__pack
                     (const UpgradeRebootSync   *message,
                      uint8_t             *out);
size_t upgrade_reboot_sync__pack_to_buffer
                     (const UpgradeRebootSync   *message,
                      ProtobufCBuffer     *buffer);
UpgradeRebootSync *
       upgrade_reboot_sync__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   upgrade_reboot_sync__free_unpacked
                     (UpgradeRebootSync *message,
                      ProtobufCAllocator *allocator);
/* ExportLogState methods */
void   export_log_state__init
                     (ExportLogState         *message);
size_t export_log_state__get_packed_size
                     (const ExportLogState   *message);
size_t export_log_state__pack
                     (const ExportLogState   *message,
                      uint8_t             *out);
size_t export_log_state__pack_to_buffer
                     (const ExportLogState   *message,
                      ProtobufCBuffer     *buffer);
ExportLogState *
       export_log_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   export_log_state__free_unpacked
                     (ExportLogState *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ServerTest_Closure)
                 (const ServerTest *message,
                  void *closure_data);
typedef void (*GeneralRes_Closure)
                 (const GeneralRes *message,
                  void *closure_data);
typedef void (*SendString_Closure)
                 (const SendString *message,
                  void *closure_data);
typedef void (*MaterialPrefer_Closure)
                 (const MaterialPrefer *message,
                  void *closure_data);
typedef void (*MaterialPreferList_Closure)
                 (const MaterialPreferList *message,
                  void *closure_data);
typedef void (*TempAutoPidPrefer_Closure)
                 (const TempAutoPidPrefer *message,
                  void *closure_data);
typedef void (*TempAutoPidPreferList_Closure)
                 (const TempAutoPidPreferList *message,
                  void *closure_data);
typedef void (*DelayImagePrefer_Closure)
                 (const DelayImagePrefer *message,
                  void *closure_data);
typedef void (*PowerLossPrefer_Closure)
                 (const PowerLossPrefer *message,
                  void *closure_data);
typedef void (*AiControlPrefer_Closure)
                 (const AiControlPrefer *message,
                  void *closure_data);
typedef void (*WifiInfo_Closure)
                 (const WifiInfo *message,
                  void *closure_data);
typedef void (*NetworksInfo_Closure)
                 (const NetworksInfo *message,
                  void *closure_data);
typedef void (*SystemConfigProto_Closure)
                 (const SystemConfigProto *message,
                  void *closure_data);
typedef void (*AxisPositionInfo_Closure)
                 (const AxisPositionInfo *message,
                  void *closure_data);
typedef void (*PidInfo_Closure)
                 (const PidInfo *message,
                  void *closure_data);
typedef void (*Extruder_Closure)
                 (const Extruder *message,
                  void *closure_data);
typedef void (*HeaterBed_Closure)
                 (const HeaterBed *message,
                  void *closure_data);
typedef void (*MultiFan_Closure)
                 (const MultiFan *message,
                  void *closure_data);
typedef void (*MultiGsensor_Closure)
                 (const MultiGsensor *message,
                  void *closure_data);
typedef void (*PrintWorkInfo_Closure)
                 (const PrintWorkInfo *message,
                  void *closure_data);
typedef void (*PrintSavePara_Closure)
                 (const PrintSavePara *message,
                  void *closure_data);
typedef void (*SyncPrintState_Closure)
                 (const SyncPrintState *message,
                  void *closure_data);
typedef void (*AppControlPrint_Closure)
                 (const AppControlPrint *message,
                  void *closure_data);
typedef void (*GetGcodeFIleList_Closure)
                 (const GetGcodeFIleList *message,
                  void *closure_data);
typedef void (*LocalGcodeInfo_Closure)
                 (const LocalGcodeInfo *message,
                  void *closure_data);
typedef void (*SystemSetting_Closure)
                 (const SystemSetting *message,
                  void *closure_data);
typedef void (*LoadQuitMaterial_Closure)
                 (const LoadQuitMaterial *message,
                  void *closure_data);
typedef void (*DisControlPrint_Closure)
                 (const DisControlPrint *message,
                  void *closure_data);
typedef void (*AutoPidResult_Closure)
                 (const AutoPidResult *message,
                  void *closure_data);
typedef void (*ReportAutoLevelRes_Closure)
                 (const ReportAutoLevelRes *message,
                  void *closure_data);
typedef void (*UpgradeInfo_Closure)
                 (const UpgradeInfo *message,
                  void *closure_data);
typedef void (*UpgradeInfoList_Closure)
                 (const UpgradeInfoList *message,
                  void *closure_data);
typedef void (*HistoryRecord_Closure)
                 (const HistoryRecord *message,
                  void *closure_data);
typedef void (*HistoryRecordList_Closure)
                 (const HistoryRecordList *message,
                  void *closure_data);
typedef void (*DelayImageInfo_Closure)
                 (const DelayImageInfo *message,
                  void *closure_data);
typedef void (*DelayImageInfoList_Closure)
                 (const DelayImageInfoList *message,
                  void *closure_data);
typedef void (*MutableTypeData_Closure)
                 (const MutableTypeData *message,
                  void *closure_data);
typedef void (*UpdataErrorInfo_Closure)
                 (const UpdataErrorInfo *message,
                  void *closure_data);
typedef void (*MultipleBedTemp_Closure)
                 (const MultipleBedTemp *message,
                  void *closure_data);
typedef void (*WebControlPrint_Closure)
                 (const WebControlPrint *message,
                  void *closure_data);
typedef void (*FileControl_Closure)
                 (const FileControl *message,
                  void *closure_data);
typedef void (*DownloadGcode_Closure)
                 (const DownloadGcode *message,
                  void *closure_data);
typedef void (*UpgradeRebootSync_Closure)
                 (const UpgradeRebootSync *message,
                  void *closure_data);
typedef void (*ExportLogState_Closure)
                 (const ExportLogState *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor server_test__descriptor;
extern const ProtobufCMessageDescriptor general_res__descriptor;
extern const ProtobufCMessageDescriptor send_string__descriptor;
extern const ProtobufCMessageDescriptor material_prefer__descriptor;
extern const ProtobufCMessageDescriptor material_prefer_list__descriptor;
extern const ProtobufCMessageDescriptor temp_auto_pid_prefer__descriptor;
extern const ProtobufCMessageDescriptor temp_auto_pid_prefer_list__descriptor;
extern const ProtobufCMessageDescriptor delay_image_prefer__descriptor;
extern const ProtobufCMessageDescriptor power_loss_prefer__descriptor;
extern const ProtobufCMessageDescriptor ai_control_prefer__descriptor;
extern const ProtobufCMessageDescriptor wifi_info__descriptor;
extern const ProtobufCMessageDescriptor networks_info__descriptor;
extern const ProtobufCMessageDescriptor system_config_proto__descriptor;
extern const ProtobufCMessageDescriptor axis_position_info__descriptor;
extern const ProtobufCMessageDescriptor pid_info__descriptor;
extern const ProtobufCMessageDescriptor extruder__descriptor;
extern const ProtobufCMessageDescriptor heater_bed__descriptor;
extern const ProtobufCMessageDescriptor multi_fan__descriptor;
extern const ProtobufCMessageDescriptor multi_gsensor__descriptor;
extern const ProtobufCMessageDescriptor print_work_info__descriptor;
extern const ProtobufCMessageDescriptor print_save_para__descriptor;
extern const ProtobufCMessageDescriptor sync_print_state__descriptor;
extern const ProtobufCMessageDescriptor app_control_print__descriptor;
extern const ProtobufCMessageDescriptor get_gcode_file_list__descriptor;
extern const ProtobufCMessageDescriptor local_gcode_info__descriptor;
extern const ProtobufCMessageDescriptor system_setting__descriptor;
extern const ProtobufCMessageDescriptor load_quit_material__descriptor;
extern const ProtobufCMessageDescriptor dis_control_print__descriptor;
extern const ProtobufCMessageDescriptor auto_pid_result__descriptor;
extern const ProtobufCMessageDescriptor report_auto_level_res__descriptor;
extern const ProtobufCMessageDescriptor upgrade_info__descriptor;
extern const ProtobufCMessageDescriptor upgrade_info_list__descriptor;
extern const ProtobufCMessageDescriptor history_record__descriptor;
extern const ProtobufCMessageDescriptor history_record_list__descriptor;
extern const ProtobufCMessageDescriptor delay_image_info__descriptor;
extern const ProtobufCMessageDescriptor delay_image_info_list__descriptor;
extern const ProtobufCMessageDescriptor mutable_type_data__descriptor;
extern const ProtobufCMessageDescriptor updata_error_info__descriptor;
extern const ProtobufCMessageDescriptor multiple_bed_temp__descriptor;
extern const ProtobufCMessageDescriptor web_control_print__descriptor;
extern const ProtobufCMessageDescriptor file_control__descriptor;
extern const ProtobufCMessageDescriptor download_gcode__descriptor;
extern const ProtobufCMessageDescriptor upgrade_reboot_sync__descriptor;
extern const ProtobufCMessageDescriptor export_log_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_SystemServer_2eproto__INCLUDED */
